/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2014-5-2: 15h:12m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_bool_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_double_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_5 ;

typedef
struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_rec_6 ;

typedef struct {
anairiats_rec_6 atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_7 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_8 ;

typedef struct {
ats_int_type atslab_0 ;
} anairiats_sum_9 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__Some_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__None_vt_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__Some_vt_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_pos_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_neg_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_fn_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_fnx_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_fun_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_prfn_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_prfun_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_praxi_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_castfn_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__VK_val_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__VK_prval_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__VK_val_pos_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__VK_val_neg_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKfun_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKval_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKpraxi_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKprfun_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKprval_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKcastfn_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOfun_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOclo_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONnul_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONint_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONintinf_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONbool_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONfloat_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONstring_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONloc_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONlist_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONlablist_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONoption_9) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_bool) (ats_ptr_type, ats_bool_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_char) (ats_ptr_type, ats_char_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_double) (ats_ptr_type, ats_double_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_int) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprintf_exn) (ats_ptr_type, ats_ptr_type, ...) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_intinf_2esats__fprint_intinf) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stamp_2esats__stamp_get_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__fprint_location) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_get_int) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_get_sym) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_loc) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type aux_22 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;
static
ats_void_type aux_24 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;
static
ats_ptr_type aux0_25 (ats_ptr_type arg0) ;
static
ats_ptr_type aux1_26 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_40 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type list_map_funenv_01411_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type list_map_fun_01412_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1806(line=65, offs=13) -- 1822(line=65, offs=29)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int:
tmp0 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp0)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_1, tmp0, atslab_0, arg0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1850(line=68, offs=16) -- 1869(line=68, offs=35)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_intinf (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_intinf:
tmp1 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp1)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_2, tmp1, atslab_0, arg0) ;
return (tmp1) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_intinf] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1895(line=71, offs=14) -- 1912(line=71, offs=31)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_bool (ats_bool_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_bool:
tmp2 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp2)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_3, tmp2, atslab_0, arg0) ;
return (tmp2) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_bool] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1940(line=74, offs=16) -- 1958(line=74, offs=34)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_double (ats_double_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp3) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_double:
tmp3 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp3)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_4, tmp3, atslab_0, arg0) ;
return (tmp3) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_double] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1986(line=77, offs=16) -- 2009(line=77, offs=39)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string:
tmp4 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp4)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_2, tmp4, atslab_0, arg0) ;
return (tmp4) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2055(line=82, offs=13) -- 2075(line=82, offs=33)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_loc (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp5) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_loc:
tmp5 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp5)->tag = 6 ;
ats_selptrset_mac(anairiats_sum_2, tmp5, atslab_0, arg0) ;
return (tmp5) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_loc] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2165(line=91, offs=14) -- 2192(line=91, offs=41)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing:
tmp8 = (ats_sum_ptr_type)0 ;
tmp7 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp7, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_5, tmp7, atslab_1, tmp8) ;
tmp6 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp6)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_2, tmp6, atslab_0, tmp7) ;
return (tmp6) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2218(line=93, offs=14) -- 2256(line=93, offs=52)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair:
tmp12 = (ats_sum_ptr_type)0 ;
tmp11 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp11, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp11, atslab_1, tmp12) ;
tmp10 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp10, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_5, tmp10, atslab_1, tmp11) ;
tmp9 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp9)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_2, tmp9, atslab_0, tmp10) ;
return (tmp9) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2308(line=98, offs=17) -- 2359(line=99, offs=43)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (anairiats_rec_6, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1:
tmp15.atslab_0 = arg0 ;
tmp15.atslab_1 = arg1 ;

tmp16 = (ats_sum_ptr_type)0 ;
tmp14 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp14, atslab_0, tmp15) ;
ats_selptrset_mac(anairiats_sum_7, tmp14, atslab_1, tmp16) ;
tmp13 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp13)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp13, atslab_0, tmp14) ;
return (tmp13) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2387(line=101, offs=17) -- 2471(line=102, offs=66)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (anairiats_rec_6, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (anairiats_rec_6, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2:
tmp19.atslab_0 = arg0 ;
tmp19.atslab_1 = arg1 ;

tmp21.atslab_0 = arg2 ;
tmp21.atslab_1 = arg3 ;

tmp22 = (ats_sum_ptr_type)0 ;
tmp20 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp20, atslab_0, tmp21) ;
ats_selptrset_mac(anairiats_sum_7, tmp20, atslab_1, tmp22) ;
tmp18 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp18, atslab_0, tmp19) ;
ats_selptrset_mac(anairiats_sum_7, tmp18, atslab_1, tmp20) ;
tmp17 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp17)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp17, atslab_0, tmp18) ;
return (tmp17) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2499(line=105, offs=1) -- 2587(line=107, offs=62)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval3 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4, ats_ptr_type arg5) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (anairiats_rec_6, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (anairiats_rec_6, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (anairiats_rec_6, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval3:
tmp25.atslab_0 = arg0 ;
tmp25.atslab_1 = arg1 ;

tmp27.atslab_0 = arg2 ;
tmp27.atslab_1 = arg3 ;

tmp29.atslab_0 = arg4 ;
tmp29.atslab_1 = arg5 ;

tmp30 = (ats_sum_ptr_type)0 ;
tmp28 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp28, atslab_0, tmp29) ;
ats_selptrset_mac(anairiats_sum_7, tmp28, atslab_1, tmp30) ;
tmp26 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp26, atslab_0, tmp27) ;
ats_selptrset_mac(anairiats_sum_7, tmp26, atslab_1, tmp28) ;
tmp24 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp24, atslab_0, tmp25) ;
ats_selptrset_mac(anairiats_sum_7, tmp24, atslab_1, tmp26) ;
tmp23 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp23)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp23, atslab_0, tmp24) ;
return (tmp23) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval3] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2623(line=110, offs=1) -- 2731(line=112, offs=74)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval4 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4, ats_ptr_type arg5, ats_ptr_type arg6, ats_ptr_type arg7) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (anairiats_rec_6, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (anairiats_rec_6, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (anairiats_rec_6, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (anairiats_rec_6, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval4:
tmp33.atslab_0 = arg0 ;
tmp33.atslab_1 = arg1 ;

tmp35.atslab_0 = arg2 ;
tmp35.atslab_1 = arg3 ;

tmp37.atslab_0 = arg4 ;
tmp37.atslab_1 = arg5 ;

tmp39.atslab_0 = arg6 ;
tmp39.atslab_1 = arg7 ;

tmp40 = (ats_sum_ptr_type)0 ;
tmp38 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp38, atslab_0, tmp39) ;
ats_selptrset_mac(anairiats_sum_7, tmp38, atslab_1, tmp40) ;
tmp36 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp36, atslab_0, tmp37) ;
ats_selptrset_mac(anairiats_sum_7, tmp36, atslab_1, tmp38) ;
tmp34 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp34, atslab_0, tmp35) ;
ats_selptrset_mac(anairiats_sum_7, tmp34, atslab_1, tmp36) ;
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp32, atslab_0, tmp33) ;
ats_selptrset_mac(anairiats_sum_7, tmp32, atslab_1, tmp34) ;
tmp31 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp31)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp31, atslab_0, tmp32) ;
return (tmp31) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval4] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2787(line=118, offs=3) -- 2828(line=118, offs=44)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0:
tmp42 = (ats_sum_ptr_type)0 ;
tmp41 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp42) ;
return (tmp41) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2857(line=121, offs=3) -- 2914(line=122, offs=44)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1:
tmp45 = (ats_sum_ptr_type)0 ;
tmp44 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp44, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp44, atslab_1, tmp45) ;
tmp43 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp44) ;
return (tmp43) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2943(line=125, offs=3) -- 3012(line=126, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2:
tmp49 = (ats_sum_ptr_type)0 ;
tmp48 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp48, atslab_0, arg2) ;
ats_selptrset_mac(anairiats_sum_5, tmp48, atslab_1, tmp49) ;
tmp47 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp47, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp47, atslab_1, tmp48) ;
tmp46 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp47) ;
return (tmp46) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3041(line=129, offs=3) -- 3126(line=130, offs=60)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg3 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg3:
tmp54 = (ats_sum_ptr_type)0 ;
tmp53 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp53, atslab_0, arg3) ;
ats_selptrset_mac(anairiats_sum_5, tmp53, atslab_1, tmp54) ;
tmp52 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp52, atslab_0, arg2) ;
ats_selptrset_mac(anairiats_sum_5, tmp52, atslab_1, tmp53) ;
tmp51 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp51, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp51, atslab_1, tmp52) ;
tmp50 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp51) ;
return (tmp50) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg3] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3155(line=133, offs=3) -- 3256(line=134, offs=70)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg4 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg4:
tmp60 = (ats_sum_ptr_type)0 ;
tmp59 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp59, atslab_0, arg4) ;
ats_selptrset_mac(anairiats_sum_5, tmp59, atslab_1, tmp60) ;
tmp58 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp58, atslab_0, arg3) ;
ats_selptrset_mac(anairiats_sum_5, tmp58, atslab_1, tmp59) ;
tmp57 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp57, atslab_0, arg2) ;
ats_selptrset_mac(anairiats_sum_5, tmp57, atslab_1, tmp58) ;
tmp56 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp56, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp56, atslab_1, tmp57) ;
tmp55 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp56) ;
return (tmp55) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg4] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3290(line=138, offs=3) -- 3346(line=138, offs=59)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst:
tmp62 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp62)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_2, tmp62, atslab_0, arg1) ;
tmp61 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (arg0, tmp62) ;
return (tmp61) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3426(line=144, offs=14) -- 3449(line=144, offs=37)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none:
tmp64 = (ats_sum_ptr_type)0 ;
tmp63 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp63)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp63, atslab_0, tmp64) ;
return (tmp63) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3474(line=146, offs=14) -- 3498(line=146, offs=38)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some:
tmp66 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
ats_selptrset_mac(anairiats_sum_8, tmp66, atslab_0, arg0) ;
tmp65 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp65)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp65, atslab_0, tmp66) ;
return (tmp65) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3552(line=152, offs=3) -- 4574(line=203, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp67) ;
ATSlocal (ats_int_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
// ATSlocal_void (tmp70) ;
// ATSlocal_void (tmp71) ;
ATSlocal (ats_bool_type, tmp72) ;
ATSlocal (ats_double_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
// ATSlocal_void (tmp76) ;
// ATSlocal_void (tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
// ATSlocal_void (tmp79) ;
// ATSlocal_void (tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
// ATSlocal_void (tmp82) ;
// ATSlocal_void (tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
// ATSlocal_void (tmp85) ;
// ATSlocal_void (tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
/* tmp67 = */ atspre_fprint_string (arg0, ATSstrcst("{}")) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp68 = ats_caselptrlab_mac(anairiats_sum_1, arg1, atslab_0) ;
/* tmp67 = */ atspre_fprint_int (arg0, tmp68) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)arg1)->tag != 2) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp69 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp70 = */ atspre_fprint_char (arg0, '"') ;
/* tmp71 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_intinf_2esats__fprint_intinf (arg0, tmp69) ;
/* tmp67 = */ atspre_fprint_char (arg0, '"') ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)arg1)->tag != 3) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp72 = ats_caselptrlab_mac(anairiats_sum_3, arg1, atslab_0) ;
/* tmp67 = */ atspre_fprint_bool (arg0, tmp72) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)arg1)->tag != 4) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp73 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_0) ;
/* tmp67 = */ atspre_fprint_double (arg0, tmp73) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)arg1)->tag != 5) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp74 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp67 = */ atspre_fprintf_exn (arg0, ATSstrcst("\"%s\""), tmp74) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)arg1)->tag != 6) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp75 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp76 = */ atspre_fprint_string (arg0, ATSstrcst("\"")) ;
/* tmp77 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__fprint_location (arg0, tmp75) ;
/* tmp67 = */ atspre_fprint_string (arg0, ATSstrcst("\"")) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)arg1)->tag != 7) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp78 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp79 = */ atspre_fprint_string (arg0, ATSstrcst("[")) ;
/* tmp80 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist (arg0, tmp78) ;
/* tmp67 = */ atspre_fprint_string (arg0, ATSstrcst("]")) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)arg1)->tag != 8) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp81 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp82 = */ atspre_fprint_string (arg0, ATSstrcst("{")) ;
/* tmp83 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist (arg0, tmp81) ;
/* tmp67 = */ atspre_fprint_string (arg0, ATSstrcst("}")) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
// if (((ats_sum_ptr_type)arg1)->tag != 9) { ats_deadcode_failure_handle () ; }
__ats_lab_9_1:
tmp84 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp85 = */ atspre_fprint_string (arg0, ATSstrcst("[")) ;
do {
/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (tmp84 == (ats_sum_ptr_type)0) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp87 = ats_caselptrlab_mac(anairiats_sum_8, tmp84, atslab_0) ;
/* tmp86 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp87) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
// if (tmp84 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_11_1:
break ;
} while (0) ;
/* tmp67 = */ atspre_fprint_string (arg0, ATSstrcst("]")) ;
break ;
} while (0) ;
return /* (tmp67) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 4678(line=211, offs=5) -- 4986(line=230, offs=4)
*/
ATSstaticdec()
ats_void_type
aux_22 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
// ATSlocal_void (tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;
// ATSlocal_void (tmp92) ;
ATSlocal (ats_bool_type, tmp93) ;
// ATSlocal_void (tmp94) ;
ATSlocal (ats_int_type, tmp95) ;

__ats_lab_aux_22:
do {
/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (arg1 != (ats_sum_ptr_type)0) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
// if (arg1 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_13_1:
tmp90 = ats_caselptrlab_mac(anairiats_sum_5, arg1, atslab_0) ;
tmp91 = ats_caselptrlab_mac(anairiats_sum_5, arg1, atslab_1) ;
tmp93 = atspre_gt_int_int (arg2, 0) ;
if (tmp93) {
/* tmp92 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
/* tmp94 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp90) ;
tmp95 = atspre_add_int_int (arg2, 1) ;
arg0 = arg0 ;
arg1 = tmp91 ;
arg2 = tmp95 ;
goto __ats_lab_aux_22 ; // tail call
break ;
} while (0) ;
return /* (tmp89) */ ;
} /* end of [aux_22] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 4654(line=209, offs=3) -- 5032(line=234, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp88) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist:
/* tmp88 = */ aux_22 (arg0, arg1, 0) ;
return /* (tmp88) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 5143(line=242, offs=5) -- 5557(line=265, offs=4)
*/
ATSstaticdec()
ats_void_type
aux_24 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
// ATSlocal_void (tmp97) ;
ATSlocal (anairiats_rec_6, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
// ATSlocal_void (tmp100) ;
ATSlocal (ats_bool_type, tmp101) ;
// ATSlocal_void (tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
// ATSlocal_void (tmp104) ;
// ATSlocal_void (tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_int_type, tmp107) ;

__ats_lab_aux_24:
do {
/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (arg1 != (ats_sum_ptr_type)0) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
// if (arg1 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_15_1:
tmp98 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_0) ;
tmp99 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_1) ;
tmp101 = atspre_gt_int_int (arg2, 0) ;
if (tmp101) {
/* tmp100 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
tmp103 = ats_select_mac(tmp98, atslab_0) ;
/* tmp102 = */ atspre_fprintf_exn (arg0, ATSstrcst("\"%s\""), tmp103) ;
/* tmp104 = */ atspre_fprint_string (arg0, ATSstrcst(": ")) ;
tmp106 = ats_select_mac(tmp98, atslab_1) ;
/* tmp105 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp106) ;
tmp107 = atspre_add_int_int (arg2, 1) ;
arg0 = arg0 ;
arg1 = tmp99 ;
arg2 = tmp107 ;
goto __ats_lab_aux_24 ; // tail call
break ;
} while (0) ;
return /* (tmp97) */ ;
} /* end of [aux_24] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 5118(line=240, offs=3) -- 5604(line=269, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp96) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist:
/* tmp96 = */ aux_24 (arg0, arg1, 0) ;
return /* (tmp96) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 5671(line=275, offs=5) -- 5854(line=283, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux0_25 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;

__ats_lab_aux0_25:
tmp109 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp111 = (ats_sum_ptr_type)0 ;
tmp110 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp110)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_2, tmp110, atslab_0, tmp111) ;
tmp108 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("funclo_name"), tmp109, ATSstrcst("funclo_arglst"), tmp110) ;
return (tmp108) ;
} /* end of [aux0_25] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 5877(line=285, offs=5) -- 6071(line=293, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux1_26 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp112) ;
ATSlocal (ats_ptr_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;

__ats_lab_aux1_26:
tmp113 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp114 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing (arg1) ;
tmp112 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("funclo_name"), tmp113, ATSstrcst("funclo_arglst"), tmp114) ;
return (tmp112) ;
} /* end of [aux1_26] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 6139(line=298, offs=16) -- 6261(line=302, offs=61)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funclo (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp115) ;
ATSlocal (ats_int_type, tmp116) ;
ATSlocal (ats_ptr_type, tmp117) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funclo:
do {
/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp115 = aux0_25 (ATSstrcst("FUNCLOfun")) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_17_1:
tmp116 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_0) ;
tmp117 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (tmp116) ;
tmp115 = aux1_26 (ATSstrcst("FUNCLOclo"), tmp117) ;
break ;
} while (0) ;
return (tmp115) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funclo] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 6365(line=310, offs=17) -- 6534(line=315, offs=51)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_caskind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp118) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_caskind:
do {
/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp118 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("CK_case")) ;
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp118 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("CK_case_pos")) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
// if (((ats_sum_ptr_type)arg0)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_20_1:
tmp118 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("CK_case_neg")) ;
break ;
} while (0) ;
return (tmp118) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_caskind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 6616(line=321, offs=17) -- 6953(line=334, offs=47)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp119) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funkind:
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_fn")) ;
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_fnx")) ;
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_fun")) ;
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_prfn")) ;
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_prfun")) ;
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)arg0)->tag != 5) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_praxi")) ;
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
// if (((ats_sum_ptr_type)arg0)->tag != 6) { ats_deadcode_failure_handle () ; }
__ats_lab_27_1:
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_castfn")) ;
break ;
} while (0) ;
return (tmp119) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funkind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7038(line=341, offs=17) -- 7246(line=347, offs=49)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_valkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp120) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_valkind:
do {
/* branch: __ats_lab_28 */
__ats_lab_28_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_29_0 ; }
__ats_lab_28_1:
tmp120 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("VK_val")) ;
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp120 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("VK_prval")) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_31_0 ; }
__ats_lab_30_1:
tmp120 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("VK_val_pos")) ;
break ;

/* branch: __ats_lab_31 */
__ats_lab_31_0:
// if (((ats_sum_ptr_type)arg0)->tag != 3) { ats_deadcode_failure_handle () ; }
__ats_lab_31_1:
tmp120 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("VK_val_neg")) ;
break ;
} while (0) ;
return (tmp120) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_valkind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7329(line=353, offs=18) -- 7620(line=362, offs=47)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_dcstkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp121) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_dcstkind:
do {
/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKfun")) ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_34_0 ; }
__ats_lab_33_1:
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKval")) ;
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKpraxi")) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKprfun")) ;
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKprval")) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
// if (((ats_sum_ptr_type)arg0)->tag != 5) { ats_deadcode_failure_handle () ; }
__ats_lab_37_1:
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKcastfn")) ;
break ;
} while (0) ;
return (tmp121) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_dcstkind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7706(line=369, offs=15) -- 7745(line=370, offs=33)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp122) ;
ATSlocal (ats_int_type, tmp123) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp:
tmp123 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stamp_2esats__stamp_get_int (arg0) ;
tmp122 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (tmp123) ;
return (tmp122) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7776(line=373, offs=16) -- 7822(line=374, offs=39)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp124) ;
ATSlocal (ats_ptr_type, tmp125) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol:
tmp125 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name (arg0) ;
tmp124 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (tmp125) ;
return (tmp124) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7855(line=377, offs=18) -- 7879(line=377, offs=42)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp126) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location:
tmp126 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_loc (arg0) ;
return (tmp126) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7931(line=383, offs=3) -- 8434(line=407, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_label (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp127) ;
ATSlocal (ats_ptr_type, tmp128) ;
ATSlocal (ats_int_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;
ATSlocal (ats_ptr_type, tmp132) ;
ATSlocal (ats_ptr_type, tmp133) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_label:
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_get_int (arg0) ;
do {
/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (tmp128 == (ats_sum_ptr_type)0) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp129 = ats_caselptrlab_mac(anairiats_sum_9, tmp128, atslab_0) ;
ATS_FREE(tmp128) ;
tmp130 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (tmp129) ;
tmp127 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (ATSstrcst("LABint"), tmp130) ;
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
// if (tmp128 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_39_1:
tmp131 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_get_sym (arg0) ;
do {
/* branch: __ats_lab_40 */
__ats_lab_40_0:
if (tmp131 == (ats_sum_ptr_type)0) { goto __ats_lab_41_0 ; }
__ats_lab_40_1:
tmp132 = ats_caselptrlab_mac(anairiats_sum_8, tmp131, atslab_0) ;
ATS_FREE(tmp131) ;
tmp133 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (tmp132) ;
tmp127 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (ATSstrcst("LABsym"), tmp133) ;
break ;

/* branch: __ats_lab_41 */
__ats_lab_41_0:
// if (tmp131 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_41_1:
tmp127 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONnul_0) ;
break ;
} while (0) ;
break ;
} while (0) ;
return (tmp127) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_label] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 8509(line=412, offs=17) -- 8534(line=412, offs=42)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp134) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored:
tmp134 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONnul_0) ;
return (tmp134) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 52519(line=1874, offs=5) -- 52952(line=1891, offs=4)
*/
ATSstaticdec()
ats_void_type
loop_40 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp139) ;
ATSlocal (ats_ptr_type, tmp140) ;
ATSlocal (ats_ptr_type, tmp141) ;
ATSlocal (ats_ptr_type, tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;
ATSlocal (ats_ptr_type, tmp144) ;
ATSlocal (ats_ptr_type, tmp145) ;

__ats_lab_loop_40:
do {
/* branch: __ats_lab_42 */
__ats_lab_42_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_43_0 ; }
__ats_lab_42_1:
tmp140 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_0) ;
tmp141 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_1) ;
tmp142 = ((ats_ptr_type(*)(ats_ptr_type, ats_ptr_type))arg1) (tmp140, arg3) ;
tmp143 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp143, atslab_0, tmp142) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp143 ;
// if (ats_ptrget_mac(ats_ptr_type, arg2) == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp144 = &ats_caselptrlab_mac(anairiats_sum_5, ats_ptrget_mac(ats_ptr_type, arg2), atslab_1) ;
arg0 = tmp141 ;
arg1 = arg1 ;
arg2 = tmp144 ;
arg3 = arg3 ;
goto __ats_lab_loop_40 ; // tail call
break ;

/* branch: __ats_lab_43 */
__ats_lab_43_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_43_1:
tmp145 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp145 ;
break ;
} while (0) ;
return /* (tmp139) */ ;
} /* end of [loop_40] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 52444(line=1870, offs=3) -- 53099(line=1899, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_map_funenv_01411_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp138) ;
ATSlocal (ats_ptr_type, tmp146) ;
// ATSlocal_void (tmp147) ;

__ats_lab_list_map_funenv_01411_ats_ptr_type_ats_ptr_type:
/* ats_ptr_type tmp146 ; */
/* tmp147 = */ loop_40 (arg0, arg1, (&tmp146), arg2) ;
tmp138 = tmp146 ;
return (tmp138) ;
} /* end of [list_map_funenv_01411_ats_ptr_type_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 53173(line=1904, offs=3) -- 53424(line=1911, offs=2)
*/
ATSstaticdec()
ats_ptr_type
list_map_fun_01412_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp137) ;

__ats_lab_list_map_fun_01412_ats_ptr_type_ats_ptr_type:
tmp137 = list_map_funenv_01411_ats_ptr_type_ats_ptr_type (arg0, ats_castfn_mac(ats_ptr_type, arg1), atspre_null_ptr) ;
return (tmp137) ;
} /* end of [list_map_fun_01412_ats_ptr_type_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 8591(line=418, offs=7) -- 8687(line=424, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp135) ;
ATSlocal (ats_ptr_type, tmp136) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun:
tmp136 = list_map_fun_01412_ats_ptr_type_ats_ptr_type (arg0, arg1) ;
tmp135 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp135)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_2, tmp135, atslab_0, ats_castfn_mac(ats_ptr_type, tmp136)) ;
return (tmp135) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 8774(line=430, offs=7) -- 8877(line=437, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp148) ;
ATSlocal (ats_ptr_type, tmp149) ;
ATSlocal (ats_ptr_type, tmp150) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun:
do {
/* branch: __ats_lab_44 */
__ats_lab_44_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_45_0 ; }
__ats_lab_44_1:
tmp148 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none () ;
break ;

/* branch: __ats_lab_45 */
__ats_lab_45_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_45_1:
tmp149 = ats_caselptrlab_mac(anairiats_sum_8, arg0, atslab_0) ;
tmp150 = ((ats_ptr_type(*)(ats_ptr_type))arg1) (tmp149) ;
tmp148 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some (tmp150) ;
break ;
} while (0) ;
return (tmp148) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_intinf_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stamp_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_intinf_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stamp_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_jsonize_dats.c] */
