/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-12-6: 14h:23m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_5 ;

typedef
struct {
ats_ptr_type atslab_c3nstroptref_loc ;
ats_ptr_type atslab_c3nstroptref_ref ;
} anairiats_rec_6 ;

typedef
struct {
ats_ptr_type atslab_h3ypo_loc ;
ats_ptr_type atslab_h3ypo_node ;
} anairiats_rec_7 ;

typedef
struct {
ats_ptr_type atslab_c3nstr_loc ;
ats_ptr_type atslab_c3nstr_kind ;
ats_ptr_type atslab_c3nstr_node ;
} anairiats_rec_8 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_9 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__Some_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDmain_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDcase_exhaustiveness_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDtermet_isnat_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDtermet_isdec_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_fin_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_lvar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDsome_vbox_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDlstate_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDlstate_var_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRKINDloop_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__H3YPOprop_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__H3YPObind_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__H3YPOeqeq_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRprop_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__C3NSTRitmlst_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMsvar_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMhypo_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMsVar_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMcnstr_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMcnstr_ref_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__S3ITMdisj_5) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_newline) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_list) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_caskind) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2Var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__jsonize_d2var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__jsonize_c3nstr) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type aux0_1 (ats_ptr_type arg0) ;
static
ats_ptr_type aux1_2 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux2_3 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type aux3_4 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type aux0_6 (ats_ptr_type arg0) ;
static
ats_ptr_type aux1_7 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux2_8 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type aux1_11 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux2_12 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type auxmain_14 (ats_ptr_type arg0) ;
static
ats_ptr_type aux1_15 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type auxmain_17 (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 2688(line=101, offs=5) -- 2887(line=112, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux0_1 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab_aux0_1:
tmp2 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp4 = (ats_sum_ptr_type)0 ;
tmp3 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_list (tmp4) ;
tmp1 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("c3nstrkind_name"), tmp2, ATSstrcst("c3nstrkind_arglst"), tmp3) ;
return (tmp1) ;
} /* end of [aux0_1] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 2912(line=114, offs=5) -- 3120(line=125, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux1_2 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;

__ats_lab_aux1_2:
tmp6 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp7 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing (arg1) ;
tmp5 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("c3nstrkind_name"), tmp6, ATSstrcst("c3nstrkind_arglst"), tmp7) ;
return (tmp5) ;
} /* end of [aux1_2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 3145(line=127, offs=5) -- 3377(line=139, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux2_3 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;

__ats_lab_aux2_3:
tmp9 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp10 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair (arg1, arg2) ;
tmp8 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("c3nstrkind_name"), tmp9, ATSstrcst("c3nstrkind_arglst"), tmp10) ;
return (tmp8) ;
} /* end of [aux2_3] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 3400(line=141, offs=5) -- 3666(line=153, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux3_4 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;

__ats_lab_aux3_4:
tmp12 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp17 = (ats_sum_ptr_type)0 ;
tmp16 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp16, atslab_0, arg3) ;
ats_selptrset_mac(anairiats_sum_1, tmp16, atslab_1, tmp17) ;
tmp15 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp15, atslab_0, arg2) ;
ats_selptrset_mac(anairiats_sum_1, tmp15, atslab_1, tmp16) ;
tmp14 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
ats_selptrset_mac(anairiats_sum_1, tmp14, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_1, tmp14, atslab_1, tmp15) ;
tmp13 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_list (tmp14) ;
tmp11 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("c3nstrkind_name"), tmp12, ATSstrcst("c3nstrkind_arglst"), tmp13) ;
return (tmp11) ;
} /* end of [aux3_4] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 2669(line=99, offs=3) -- 5166(line=205, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_int_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp0 = aux0_1 (ATSstrcst("C3NSTRKINDmain")) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp18 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp19 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
tmp20 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_caskind (tmp18) ;
tmp21 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored (tmp19) ;
tmp0 = aux2_3 (ATSstrcst("C3NSTRKINDcase_exhaustiveness"), tmp20, tmp21) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp0 = aux0_1 (ATSstrcst("C3NSTRKINDtermet_isnat")) ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp0 = aux0_1 (ATSstrcst("C3NSTRKINDtermet_isdec")) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp22 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp23 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp24 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_2) ;
tmp25 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__jsonize_d2var (tmp22) ;
tmp26 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp23) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp24) ;
tmp0 = aux3_4 (ATSstrcst("C3NSTRKINDsome_fin"), tmp25, tmp26, tmp27) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)arg0)->tag != 5) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp28 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp29 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp30 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_2) ;
tmp31 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__jsonize_d2var (tmp28) ;
tmp32 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp29) ;
tmp33 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp30) ;
tmp0 = aux3_4 (ATSstrcst("C3NSTRKINDsome_lvar"), tmp31, tmp32, tmp33) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)arg0)->tag != 6) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp34 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp35 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp36 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_2) ;
tmp37 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__jsonize_d2var (tmp34) ;
tmp38 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp35) ;
tmp39 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp36) ;
tmp0 = aux3_4 (ATSstrcst("C3NSTRKINDsome_vbox"), tmp37, tmp38, tmp39) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)arg0)->tag != 7) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp0 = aux0_1 (ATSstrcst("C3NSTRKINDlstate")) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)arg0)->tag != 8) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp40 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp41 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__jsonize_d2var (tmp40) ;
tmp0 = aux1_2 (ATSstrcst("C3NSTRKINDlstate_var"), tmp41) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
// if (((ats_sum_ptr_type)arg0)->tag != 9) { ats_deadcode_failure_handle () ; }
__ats_lab_9_1:
tmp42 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_0) ;
tmp43 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (tmp42) ;
tmp0 = aux1_2 (ATSstrcst("C3NSTRKINDlloop"), tmp43) ;
break ;
} while (0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 5805(line=236, offs=5) -- 5994(line=247, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux0_6 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;

__ats_lab_aux0_6:
tmp46 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp48 = (ats_sum_ptr_type)0 ;
tmp47 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_list (tmp48) ;
tmp45 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("s3itm_name"), tmp46, ATSstrcst("s3itm_arglst"), tmp47) ;
return (tmp45) ;
} /* end of [aux0_6] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 6019(line=249, offs=5) -- 6217(line=260, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux1_7 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;

__ats_lab_aux1_7:
tmp50 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp51 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing (arg1) ;
tmp49 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("s3itm_name"), tmp50, ATSstrcst("s3itm_arglst"), tmp51) ;
return (tmp49) ;
} /* end of [aux1_7] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 6242(line=262, offs=5) -- 6464(line=274, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux2_8 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;

__ats_lab_aux2_8:
tmp53 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp54 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair (arg1, arg2) ;
tmp52 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("s3itm_name"), tmp53, ATSstrcst("s3itm_arglst"), tmp54) ;
return (tmp52) ;
} /* end of [aux2_8] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 5786(line=234, offs=15) -- 7121(line=304, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm:
do {
/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp55 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp56 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2var (tmp55) ;
tmp44 = aux1_7 (ATSstrcst("S3ITMsvar"), tmp56) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp57 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp58 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo (tmp57) ;
tmp44 = aux1_7 (ATSstrcst("S3ITMsvar"), tmp58) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp59 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp60 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2Var (tmp59) ;
tmp44 = aux1_7 (ATSstrcst("S3ITMsvar"), tmp60) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp61 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp62 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__jsonize_c3nstr (tmp61) ;
tmp44 = aux1_7 (ATSstrcst("S3ITMcnstr"), tmp62) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp63 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp64 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, tmp63), atslab_c3nstroptref_loc) ;
tmp65 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, tmp63), atslab_c3nstroptref_ref) ;
tmp66 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location (tmp64) ;
tmp68 = ats_ptrget_mac(ats_ptr_type, tmp65) ;
tmp67 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt (tmp68) ;
tmp44 = aux2_8 (ATSstrcst("S3ITMcnstr_ref"), tmp66, tmp67) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
// if (((ats_sum_ptr_type)arg0)->tag != 5) { ats_deadcode_failure_handle () ; }
__ats_lab_15_1:
tmp69 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp70 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst (tmp69) ;
tmp44 = aux1_7 (ATSstrcst("S3ITMdisj"), tmp70) ;
break ;
} while (0) ;
return (tmp44) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 7201(line=310, offs=3) -- 7248(line=310, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp71) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst:
tmp71 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm) ;
return (tmp71) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 7281(line=313, offs=3) -- 7333(line=313, offs=55)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp72) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst:
tmp72 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst) ;
return (tmp72) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 7369(line=319, offs=5) -- 7565(line=329, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux1_11 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;

__ats_lab_aux1_11:
tmp74 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp75 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing (arg1) ;
tmp73 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("h3ypo_name"), tmp74, ATSstrcst("h3ypo_arglst"), tmp75) ;
return (tmp73) ;
} /* end of [aux1_11] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 7590(line=331, offs=5) -- 7810(line=342, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux2_12 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;

__ats_lab_aux2_12:
tmp77 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp78 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair (arg1, arg2) ;
tmp76 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("h3ypo_name"), tmp77, ATSstrcst("h3ypo_arglst"), tmp78) ;
return (tmp76) ;
} /* end of [aux2_12] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 7899(line=350, offs=5) -- 8583(line=376, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxmain_14 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;

__ats_lab_auxmain_14:
tmp81 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_7, arg0), atslab_h3ypo_node) ;
do {
/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp81)->tag != 0) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp82 = ats_caselptrlab_mac(anairiats_sum_4, tmp81, atslab_0) ;
tmp83 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp82) ;
tmp80 = aux1_11 (ATSstrcst("H3YPOprop"), tmp83) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)tmp81)->tag != 1) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp84 = ats_caselptrlab_mac(anairiats_sum_2, tmp81, atslab_0) ;
tmp85 = ats_caselptrlab_mac(anairiats_sum_2, tmp81, atslab_1) ;
tmp86 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2var (tmp84) ;
tmp87 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp85) ;
tmp80 = aux2_12 (ATSstrcst("H3YPObind"), tmp86, tmp87) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
// if (((ats_sum_ptr_type)tmp81)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_18_1:
tmp88 = ats_caselptrlab_mac(anairiats_sum_2, tmp81, atslab_0) ;
tmp89 = ats_caselptrlab_mac(anairiats_sum_2, tmp81, atslab_1) ;
tmp90 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp88) ;
tmp91 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp89) ;
tmp80 = aux2_12 (ATSstrcst("H3YPOeqeq"), tmp90, tmp91) ;
break ;
} while (0) ;
return (tmp80) ;
} /* end of [auxmain_14] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 7879(line=348, offs=3) -- 8756(line=384, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo:
tmp92 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_7, arg0), atslab_h3ypo_loc) ;
tmp93 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location (tmp92) ;
tmp94 = auxmain_14 (arg0) ;
tmp79 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("h3ypo_loc"), tmp93, ATSstrcst("h3ypo_node"), tmp94) ;
return (tmp79) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 8839(line=392, offs=5) -- 9033(line=400, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux1_15 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;

__ats_lab_aux1_15:
tmp96 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp97 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing (arg1) ;
tmp95 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("c3nstr_name"), tmp96, ATSstrcst("c3nstr_arglst"), tmp97) ;
return (tmp95) ;
} /* end of [aux1_15] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 9123(line=408, offs=5) -- 9491(line=428, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxmain_17 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_ptr_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;

__ats_lab_auxmain_17:
tmp100 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, arg0), atslab_c3nstr_node) ;
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)tmp100)->tag != 0) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp101 = ats_caselptrlab_mac(anairiats_sum_4, tmp100, atslab_0) ;
tmp102 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (tmp101) ;
tmp99 = aux1_15 (ATSstrcst("C3NSTRprop"), tmp102) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
// if (((ats_sum_ptr_type)tmp100)->tag != 1) { ats_deadcode_failure_handle () ; }
__ats_lab_20_1:
tmp103 = ats_caselptrlab_mac(anairiats_sum_4, tmp100, atslab_0) ;
tmp104 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst (tmp103) ;
tmp99 = aux1_15 (ATSstrcst("C3NSTRitmlst"), tmp104) ;
break ;
} while (0) ;
return (tmp99) ;
} /* end of [auxmain_17] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 9103(line=406, offs=3) -- 9667(line=436, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__jsonize_c3nstr (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__jsonize_c3nstr:
tmp105 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, arg0), atslab_c3nstr_loc) ;
tmp106 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location (tmp105) ;
tmp107 = auxmain_17 (arg0) ;
tmp98 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("c3nstr_loc"), tmp106, ATSstrcst("c3nstr_node"), tmp107) ;
return (tmp98) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__jsonize_c3nstr] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 9770(line=444, offs=3) -- 9888(line=451, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt:
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
tmp108 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none () ;
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_22_1:
tmp109 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_0) ;
tmp110 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__jsonize_c3nstr (tmp109) ;
tmp108 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some (tmp110) ;
break ;
} while (0) ;
return (tmp108) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt] */

/*
// /home/hwxi/research/Postiats/git/src/pats_constraint3_jsonize.dats: 9967(line=457, offs=3) -- 10125(line=465, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__c3nstr_export (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;
// ATSlocal_void (tmp113) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__c3nstr_export:
tmp112 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__jsonize_c3nstr (arg1) ;
/* tmp113 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp112) ;
/* tmp111 = */ atspre_fprint_newline (arg0) ;
return /* (tmp111) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__c3nstr_export] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e11_2prelude_2SATS_2unsafe_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_constraint3_jsonize_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_constraint3_jsonize_dats.c] */
