/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2015-1-4:  0h:57m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_bool_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_double_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_5 ;

typedef
struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_rec_6 ;

typedef struct {
anairiats_rec_6 atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_7 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_8 ;

typedef struct {
ats_int_type atslab_0 ;
} anairiats_sum_9 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__Some_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__None_vt_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__Some_vt_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_pos_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_neg_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_fn_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_fnx_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_fun_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_prfn_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_prfun_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_praxi_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FK_castfn_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__VK_val_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__VK_prval_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__VK_val_pos_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__VK_val_neg_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKfun_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKval_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKpraxi_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKprfun_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKprval_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__DCKcastfn_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOfun_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOclo_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONnul_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONint_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONintinf_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONbool_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONfloat_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONstring_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONlocation_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONfilename_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONlist_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONlablist_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONoption_10) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_bool) (ats_ptr_type, ats_bool_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_char) (ats_ptr_type, ats_char_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_double) (ats_ptr_type, ats_double_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_int) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprintf_exn) (ats_ptr_type, ats_ptr_type, ...) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_intinf_2esats__fprint_intinf) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stamp_2esats__stamp_get_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__fprint_location) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_get_int) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_get_sym) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_location) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_filename) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun) (ats_ptr_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type aux_27 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;
static
ats_void_type aux_29 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;
static
ats_ptr_type aux0_30 (ats_ptr_type arg0) ;
static
ats_ptr_type aux1_31 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_47 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type list_map_funenv_01411_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type list_map_fun_01412_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1837(line=66, offs=13) -- 1853(line=66, offs=29)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int:
tmp0 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp0)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_1, tmp0, atslab_0, arg0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1881(line=69, offs=16) -- 1900(line=69, offs=35)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_intinf (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_intinf:
tmp1 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp1)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_2, tmp1, atslab_0, arg0) ;
return (tmp1) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_intinf] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1926(line=72, offs=14) -- 1943(line=72, offs=31)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_bool (ats_bool_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_bool:
tmp2 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp2)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_3, tmp2, atslab_0, arg0) ;
return (tmp2) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_bool] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 1971(line=75, offs=16) -- 1989(line=75, offs=34)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_double (ats_double_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp3) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_double:
tmp3 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp3)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_4, tmp3, atslab_0, arg0) ;
return (tmp3) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_double] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2017(line=78, offs=16) -- 2040(line=78, offs=39)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string:
tmp4 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp4)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_2, tmp4, atslab_0, arg0) ;
return (tmp4) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2091(line=83, offs=18) -- 2116(line=83, offs=43)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_location (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp5) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_location:
tmp5 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp5)->tag = 6 ;
ats_selptrset_mac(anairiats_sum_2, tmp5, atslab_0, arg0) ;
return (tmp5) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_location] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2145(line=85, offs=18) -- 2170(line=85, offs=43)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_filename (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp6) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_filename:
tmp6 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp6)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_2, tmp6, atslab_0, arg0) ;
return (tmp6) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_filename] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2311(line=97, offs=14) -- 2338(line=97, offs=41)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing:
tmp9 = (ats_sum_ptr_type)0 ;
tmp8 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp8, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_5, tmp8, atslab_1, tmp9) ;
tmp7 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp7)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp7, atslab_0, tmp8) ;
return (tmp7) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2364(line=99, offs=14) -- 2402(line=99, offs=52)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair:
tmp13 = (ats_sum_ptr_type)0 ;
tmp12 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp12, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp12, atslab_1, tmp13) ;
tmp11 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp11, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_5, tmp11, atslab_1, tmp12) ;
tmp10 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp10)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp10, atslab_0, tmp11) ;
return (tmp10) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_pair] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2454(line=104, offs=17) -- 2505(line=105, offs=43)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (anairiats_rec_6, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1:
tmp16.atslab_0 = arg0 ;
tmp16.atslab_1 = arg1 ;

tmp17 = (ats_sum_ptr_type)0 ;
tmp15 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp15, atslab_0, tmp16) ;
ats_selptrset_mac(anairiats_sum_7, tmp15, atslab_1, tmp17) ;
tmp14 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp14)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp14, atslab_0, tmp15) ;
return (tmp14) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2533(line=107, offs=17) -- 2617(line=108, offs=66)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (anairiats_rec_6, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (anairiats_rec_6, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2:
tmp20.atslab_0 = arg0 ;
tmp20.atslab_1 = arg1 ;

tmp22.atslab_0 = arg2 ;
tmp22.atslab_1 = arg3 ;

tmp23 = (ats_sum_ptr_type)0 ;
tmp21 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp21, atslab_0, tmp22) ;
ats_selptrset_mac(anairiats_sum_7, tmp21, atslab_1, tmp23) ;
tmp19 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp19, atslab_0, tmp20) ;
ats_selptrset_mac(anairiats_sum_7, tmp19, atslab_1, tmp21) ;
tmp18 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp18)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp18, atslab_0, tmp19) ;
return (tmp18) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2645(line=111, offs=1) -- 2733(line=113, offs=62)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval3 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4, ats_ptr_type arg5) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (anairiats_rec_6, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (anairiats_rec_6, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (anairiats_rec_6, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval3:
tmp26.atslab_0 = arg0 ;
tmp26.atslab_1 = arg1 ;

tmp28.atslab_0 = arg2 ;
tmp28.atslab_1 = arg3 ;

tmp30.atslab_0 = arg4 ;
tmp30.atslab_1 = arg5 ;

tmp31 = (ats_sum_ptr_type)0 ;
tmp29 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp29, atslab_0, tmp30) ;
ats_selptrset_mac(anairiats_sum_7, tmp29, atslab_1, tmp31) ;
tmp27 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp27, atslab_0, tmp28) ;
ats_selptrset_mac(anairiats_sum_7, tmp27, atslab_1, tmp29) ;
tmp25 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp25, atslab_0, tmp26) ;
ats_selptrset_mac(anairiats_sum_7, tmp25, atslab_1, tmp27) ;
tmp24 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp24)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp24, atslab_0, tmp25) ;
return (tmp24) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval3] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2769(line=116, offs=1) -- 2877(line=118, offs=74)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval4 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4, ats_ptr_type arg5, ats_ptr_type arg6, ats_ptr_type arg7) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (anairiats_rec_6, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (anairiats_rec_6, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (anairiats_rec_6, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (anairiats_rec_6, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval4:
tmp34.atslab_0 = arg0 ;
tmp34.atslab_1 = arg1 ;

tmp36.atslab_0 = arg2 ;
tmp36.atslab_1 = arg3 ;

tmp38.atslab_0 = arg4 ;
tmp38.atslab_1 = arg5 ;

tmp40.atslab_0 = arg6 ;
tmp40.atslab_1 = arg7 ;

tmp41 = (ats_sum_ptr_type)0 ;
tmp39 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp39, atslab_0, tmp40) ;
ats_selptrset_mac(anairiats_sum_7, tmp39, atslab_1, tmp41) ;
tmp37 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp37, atslab_0, tmp38) ;
ats_selptrset_mac(anairiats_sum_7, tmp37, atslab_1, tmp39) ;
tmp35 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp35, atslab_0, tmp36) ;
ats_selptrset_mac(anairiats_sum_7, tmp35, atslab_1, tmp37) ;
tmp33 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp33, atslab_0, tmp34) ;
ats_selptrset_mac(anairiats_sum_7, tmp33, atslab_1, tmp35) ;
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp32)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp32, atslab_0, tmp33) ;
return (tmp32) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval4] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 2908(line=122, offs=1) -- 3039(line=126, offs=71)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval5 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4, ats_ptr_type arg5, ats_ptr_type arg6, ats_ptr_type arg7, ats_ptr_type arg8, ats_ptr_type arg9) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (anairiats_rec_6, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (anairiats_rec_6, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (anairiats_rec_6, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (anairiats_rec_6, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (anairiats_rec_6, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval5:
tmp44.atslab_0 = arg0 ;
tmp44.atslab_1 = arg1 ;

tmp46.atslab_0 = arg2 ;
tmp46.atslab_1 = arg3 ;

tmp48.atslab_0 = arg4 ;
tmp48.atslab_1 = arg5 ;

tmp50.atslab_0 = arg6 ;
tmp50.atslab_1 = arg7 ;

tmp52.atslab_0 = arg8 ;
tmp52.atslab_1 = arg9 ;

tmp53 = (ats_sum_ptr_type)0 ;
tmp51 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp51, atslab_0, tmp52) ;
ats_selptrset_mac(anairiats_sum_7, tmp51, atslab_1, tmp53) ;
tmp49 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp49, atslab_0, tmp50) ;
ats_selptrset_mac(anairiats_sum_7, tmp49, atslab_1, tmp51) ;
tmp47 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp47, atslab_0, tmp48) ;
ats_selptrset_mac(anairiats_sum_7, tmp47, atslab_1, tmp49) ;
tmp45 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp45, atslab_0, tmp46) ;
ats_selptrset_mac(anairiats_sum_7, tmp45, atslab_1, tmp47) ;
tmp43 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp43, atslab_0, tmp44) ;
ats_selptrset_mac(anairiats_sum_7, tmp43, atslab_1, tmp45) ;
tmp42 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp42)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp42, atslab_0, tmp43) ;
return (tmp42) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval5] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3068(line=130, offs=1) -- 3219(line=134, offs=83)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval6 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4, ats_ptr_type arg5, ats_ptr_type arg6, ats_ptr_type arg7, ats_ptr_type arg8, ats_ptr_type arg9, ats_ptr_type arg10, ats_ptr_type arg11) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (anairiats_rec_6, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (anairiats_rec_6, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (anairiats_rec_6, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (anairiats_rec_6, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (anairiats_rec_6, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (anairiats_rec_6, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval6:
tmp56.atslab_0 = arg0 ;
tmp56.atslab_1 = arg1 ;

tmp58.atslab_0 = arg2 ;
tmp58.atslab_1 = arg3 ;

tmp60.atslab_0 = arg4 ;
tmp60.atslab_1 = arg5 ;

tmp62.atslab_0 = arg6 ;
tmp62.atslab_1 = arg7 ;

tmp64.atslab_0 = arg8 ;
tmp64.atslab_1 = arg9 ;

tmp66.atslab_0 = arg10 ;
tmp66.atslab_1 = arg11 ;

tmp67 = (ats_sum_ptr_type)0 ;
tmp65 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp65, atslab_0, tmp66) ;
ats_selptrset_mac(anairiats_sum_7, tmp65, atslab_1, tmp67) ;
tmp63 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp63, atslab_0, tmp64) ;
ats_selptrset_mac(anairiats_sum_7, tmp63, atslab_1, tmp65) ;
tmp61 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp61, atslab_0, tmp62) ;
ats_selptrset_mac(anairiats_sum_7, tmp61, atslab_1, tmp63) ;
tmp59 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp59, atslab_0, tmp60) ;
ats_selptrset_mac(anairiats_sum_7, tmp59, atslab_1, tmp61) ;
tmp57 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp57, atslab_0, tmp58) ;
ats_selptrset_mac(anairiats_sum_7, tmp57, atslab_1, tmp59) ;
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp55, atslab_0, tmp56) ;
ats_selptrset_mac(anairiats_sum_7, tmp55, atslab_1, tmp57) ;
tmp54 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp54)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp54, atslab_0, tmp55) ;
return (tmp54) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval6] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3248(line=138, offs=1) -- 3419(line=142, offs=95)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval7 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4, ats_ptr_type arg5, ats_ptr_type arg6, ats_ptr_type arg7, ats_ptr_type arg8, ats_ptr_type arg9, ats_ptr_type arg10, ats_ptr_type arg11, ats_ptr_type arg12, ats_ptr_type arg13) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (anairiats_rec_6, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (anairiats_rec_6, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (anairiats_rec_6, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (anairiats_rec_6, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (anairiats_rec_6, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (anairiats_rec_6, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (anairiats_rec_6, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval7:
tmp70.atslab_0 = arg0 ;
tmp70.atslab_1 = arg1 ;

tmp72.atslab_0 = arg2 ;
tmp72.atslab_1 = arg3 ;

tmp74.atslab_0 = arg4 ;
tmp74.atslab_1 = arg5 ;

tmp76.atslab_0 = arg6 ;
tmp76.atslab_1 = arg7 ;

tmp78.atslab_0 = arg8 ;
tmp78.atslab_1 = arg9 ;

tmp80.atslab_0 = arg10 ;
tmp80.atslab_1 = arg11 ;

tmp82.atslab_0 = arg12 ;
tmp82.atslab_1 = arg13 ;

tmp83 = (ats_sum_ptr_type)0 ;
tmp81 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp81, atslab_0, tmp82) ;
ats_selptrset_mac(anairiats_sum_7, tmp81, atslab_1, tmp83) ;
tmp79 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp79, atslab_0, tmp80) ;
ats_selptrset_mac(anairiats_sum_7, tmp79, atslab_1, tmp81) ;
tmp77 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp77, atslab_0, tmp78) ;
ats_selptrset_mac(anairiats_sum_7, tmp77, atslab_1, tmp79) ;
tmp75 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp75, atslab_0, tmp76) ;
ats_selptrset_mac(anairiats_sum_7, tmp75, atslab_1, tmp77) ;
tmp73 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp73, atslab_0, tmp74) ;
ats_selptrset_mac(anairiats_sum_7, tmp73, atslab_1, tmp75) ;
tmp71 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp71, atslab_0, tmp72) ;
ats_selptrset_mac(anairiats_sum_7, tmp71, atslab_1, tmp73) ;
tmp69 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp69, atslab_0, tmp70) ;
ats_selptrset_mac(anairiats_sum_7, tmp69, atslab_1, tmp71) ;
tmp68 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp68)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp68, atslab_0, tmp69) ;
return (tmp68) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval7] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3448(line=146, offs=1) -- 3639(line=150, offs=107)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval8 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4, ats_ptr_type arg5, ats_ptr_type arg6, ats_ptr_type arg7, ats_ptr_type arg8, ats_ptr_type arg9, ats_ptr_type arg10, ats_ptr_type arg11, ats_ptr_type arg12, ats_ptr_type arg13, ats_ptr_type arg14, ats_ptr_type arg15) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (anairiats_rec_6, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (anairiats_rec_6, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (anairiats_rec_6, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;
ATSlocal (anairiats_rec_6, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (anairiats_rec_6, tmp94) ;
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (anairiats_rec_6, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (anairiats_rec_6, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (anairiats_rec_6, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval8:
tmp86.atslab_0 = arg0 ;
tmp86.atslab_1 = arg1 ;

tmp88.atslab_0 = arg2 ;
tmp88.atslab_1 = arg3 ;

tmp90.atslab_0 = arg4 ;
tmp90.atslab_1 = arg5 ;

tmp92.atslab_0 = arg6 ;
tmp92.atslab_1 = arg7 ;

tmp94.atslab_0 = arg8 ;
tmp94.atslab_1 = arg9 ;

tmp96.atslab_0 = arg10 ;
tmp96.atslab_1 = arg11 ;

tmp98.atslab_0 = arg12 ;
tmp98.atslab_1 = arg13 ;

tmp100.atslab_0 = arg14 ;
tmp100.atslab_1 = arg15 ;

tmp101 = (ats_sum_ptr_type)0 ;
tmp99 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp99, atslab_0, tmp100) ;
ats_selptrset_mac(anairiats_sum_7, tmp99, atslab_1, tmp101) ;
tmp97 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp97, atslab_0, tmp98) ;
ats_selptrset_mac(anairiats_sum_7, tmp97, atslab_1, tmp99) ;
tmp95 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp95, atslab_0, tmp96) ;
ats_selptrset_mac(anairiats_sum_7, tmp95, atslab_1, tmp97) ;
tmp93 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp93, atslab_0, tmp94) ;
ats_selptrset_mac(anairiats_sum_7, tmp93, atslab_1, tmp95) ;
tmp91 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp91, atslab_0, tmp92) ;
ats_selptrset_mac(anairiats_sum_7, tmp91, atslab_1, tmp93) ;
tmp89 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp89, atslab_0, tmp90) ;
ats_selptrset_mac(anairiats_sum_7, tmp89, atslab_1, tmp91) ;
tmp87 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp87, atslab_0, tmp88) ;
ats_selptrset_mac(anairiats_sum_7, tmp87, atslab_1, tmp89) ;
tmp85 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp85, atslab_0, tmp86) ;
ats_selptrset_mac(anairiats_sum_7, tmp85, atslab_1, tmp87) ;
tmp84 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp84)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_2, tmp84, atslab_0, tmp85) ;
return (tmp84) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval8] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3696(line=157, offs=3) -- 3737(line=157, offs=44)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp102) ;
ATSlocal (ats_ptr_type, tmp103) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0:
tmp103 = (ats_sum_ptr_type)0 ;
tmp102 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp103) ;
return (tmp102) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3766(line=160, offs=3) -- 3823(line=161, offs=44)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1:
tmp106 = (ats_sum_ptr_type)0 ;
tmp105 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp105, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp105, atslab_1, tmp106) ;
tmp104 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp105) ;
return (tmp104) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3852(line=164, offs=3) -- 3921(line=165, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2:
tmp110 = (ats_sum_ptr_type)0 ;
tmp109 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp109, atslab_0, arg2) ;
ats_selptrset_mac(anairiats_sum_5, tmp109, atslab_1, tmp110) ;
tmp108 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp108, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp108, atslab_1, tmp109) ;
tmp107 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp108) ;
return (tmp107) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 3950(line=168, offs=3) -- 4035(line=169, offs=60)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg3 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;
ATSlocal (ats_ptr_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg3:
tmp115 = (ats_sum_ptr_type)0 ;
tmp114 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp114, atslab_0, arg3) ;
ats_selptrset_mac(anairiats_sum_5, tmp114, atslab_1, tmp115) ;
tmp113 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp113, atslab_0, arg2) ;
ats_selptrset_mac(anairiats_sum_5, tmp113, atslab_1, tmp114) ;
tmp112 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp112, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp112, atslab_1, tmp113) ;
tmp111 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp112) ;
return (tmp111) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg3] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 4064(line=172, offs=3) -- 4165(line=173, offs=70)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg4 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp116) ;
ATSlocal (ats_ptr_type, tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;
ATSlocal (ats_ptr_type, tmp121) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg4:
tmp121 = (ats_sum_ptr_type)0 ;
tmp120 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp120, atslab_0, arg4) ;
ats_selptrset_mac(anairiats_sum_5, tmp120, atslab_1, tmp121) ;
tmp119 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp119, atslab_0, arg3) ;
ats_selptrset_mac(anairiats_sum_5, tmp119, atslab_1, tmp120) ;
tmp118 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp118, atslab_0, arg2) ;
ats_selptrset_mac(anairiats_sum_5, tmp118, atslab_1, tmp119) ;
tmp117 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp117, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_5, tmp117, atslab_1, tmp118) ;
tmp116 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (arg0, tmp117) ;
return (tmp116) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg4] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 4199(line=177, offs=3) -- 4255(line=177, offs=59)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp122) ;
ATSlocal (ats_ptr_type, tmp123) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst:
tmp123 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp123)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp123, atslab_0, arg1) ;
tmp122 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (arg0, tmp123) ;
return (tmp122) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarglst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 4335(line=183, offs=14) -- 4358(line=183, offs=37)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp124) ;
ATSlocal (ats_ptr_type, tmp125) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none:
tmp125 = (ats_sum_ptr_type)0 ;
tmp124 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp124)->tag = 10 ;
ats_selptrset_mac(anairiats_sum_2, tmp124, atslab_0, tmp125) ;
return (tmp124) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 4383(line=185, offs=14) -- 4407(line=185, offs=38)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp126) ;
ATSlocal (ats_ptr_type, tmp127) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some:
tmp127 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
ats_selptrset_mac(anairiats_sum_8, tmp127, atslab_0, arg0) ;
tmp126 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp126)->tag = 10 ;
ats_selptrset_mac(anairiats_sum_2, tmp126, atslab_0, tmp127) ;
return (tmp126) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 4461(line=191, offs=3) -- 5646(line=248, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp128) ;
ATSlocal (ats_int_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;
// ATSlocal_void (tmp131) ;
// ATSlocal_void (tmp132) ;
ATSlocal (ats_bool_type, tmp133) ;
ATSlocal (ats_double_type, tmp134) ;
ATSlocal (ats_ptr_type, tmp135) ;
ATSlocal (ats_ptr_type, tmp136) ;
// ATSlocal_void (tmp137) ;
// ATSlocal_void (tmp138) ;
ATSlocal (ats_ptr_type, tmp139) ;
// ATSlocal_void (tmp140) ;
// ATSlocal_void (tmp141) ;
ATSlocal (ats_ptr_type, tmp142) ;
// ATSlocal_void (tmp143) ;
// ATSlocal_void (tmp144) ;
ATSlocal (ats_ptr_type, tmp145) ;
// ATSlocal_void (tmp146) ;
// ATSlocal_void (tmp147) ;
ATSlocal (ats_ptr_type, tmp148) ;
// ATSlocal_void (tmp149) ;
// ATSlocal_void (tmp150) ;
ATSlocal (ats_ptr_type, tmp151) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
/* tmp128 = */ atspre_fprint_string (arg0, ATSstrcst("{}")) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp129 = ats_caselptrlab_mac(anairiats_sum_1, arg1, atslab_0) ;
/* tmp128 = */ atspre_fprint_int (arg0, tmp129) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)arg1)->tag != 2) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp130 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp131 = */ atspre_fprint_char (arg0, '"') ;
/* tmp132 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_intinf_2esats__fprint_intinf (arg0, tmp130) ;
/* tmp128 = */ atspre_fprint_char (arg0, '"') ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)arg1)->tag != 3) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp133 = ats_caselptrlab_mac(anairiats_sum_3, arg1, atslab_0) ;
/* tmp128 = */ atspre_fprint_bool (arg0, tmp133) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)arg1)->tag != 4) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp134 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_0) ;
/* tmp128 = */ atspre_fprint_double (arg0, tmp134) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)arg1)->tag != 5) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp135 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp128 = */ atspre_fprintf_exn (arg0, ATSstrcst("\"%s\""), tmp135) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)arg1)->tag != 6) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp136 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp137 = */ atspre_fprint_string (arg0, ATSstrcst("\"")) ;
/* tmp138 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__fprint_location (arg0, tmp136) ;
/* tmp128 = */ atspre_fprint_string (arg0, ATSstrcst("\"")) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)arg1)->tag != 7) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp139 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp140 = */ atspre_fprint_string (arg0, ATSstrcst("\"")) ;
/* tmp141 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__fprint_filename_full (arg0, tmp139) ;
/* tmp128 = */ atspre_fprint_string (arg0, ATSstrcst("\"")) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)arg1)->tag != 8) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp142 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp143 = */ atspre_fprint_string (arg0, ATSstrcst("[")) ;
/* tmp144 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist (arg0, tmp142) ;
/* tmp128 = */ atspre_fprint_string (arg0, ATSstrcst("]")) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)arg1)->tag != 9) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp145 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp146 = */ atspre_fprint_string (arg0, ATSstrcst("{")) ;
/* tmp147 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist (arg0, tmp145) ;
/* tmp128 = */ atspre_fprint_string (arg0, ATSstrcst("}")) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
// if (((ats_sum_ptr_type)arg1)->tag != 10) { ats_deadcode_failure_handle () ; }
__ats_lab_10_1:
tmp148 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
/* tmp149 = */ atspre_fprint_string (arg0, ATSstrcst("[")) ;
do {
/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (tmp148 == (ats_sum_ptr_type)0) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp151 = ats_caselptrlab_mac(anairiats_sum_8, tmp148, atslab_0) ;
/* tmp150 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp151) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
// if (tmp148 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_12_1:
break ;
} while (0) ;
/* tmp128 = */ atspre_fprint_string (arg0, ATSstrcst("]")) ;
break ;
} while (0) ;
return /* (tmp128) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 5750(line=256, offs=5) -- 6058(line=275, offs=4)
*/
ATSstaticdec()
ats_void_type
aux_27 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
// ATSlocal_void (tmp153) ;
ATSlocal (ats_ptr_type, tmp154) ;
ATSlocal (ats_ptr_type, tmp155) ;
// ATSlocal_void (tmp156) ;
ATSlocal (ats_bool_type, tmp157) ;
// ATSlocal_void (tmp158) ;
ATSlocal (ats_int_type, tmp159) ;

__ats_lab_aux_27:
do {
/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (arg1 != (ats_sum_ptr_type)0) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
// if (arg1 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_14_1:
tmp154 = ats_caselptrlab_mac(anairiats_sum_5, arg1, atslab_0) ;
tmp155 = ats_caselptrlab_mac(anairiats_sum_5, arg1, atslab_1) ;
tmp157 = atspre_gt_int_int (arg2, 0) ;
if (tmp157) {
/* tmp156 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
/* tmp158 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp154) ;
tmp159 = atspre_add_int_int (arg2, 1) ;
arg0 = arg0 ;
arg1 = tmp155 ;
arg2 = tmp159 ;
goto __ats_lab_aux_27 ; // tail call
break ;
} while (0) ;
return /* (tmp153) */ ;
} /* end of [aux_27] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 5726(line=254, offs=3) -- 6104(line=279, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp152) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist:
/* tmp152 = */ aux_27 (arg0, arg1, 0) ;
return /* (tmp152) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonvalist] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 6215(line=287, offs=5) -- 6629(line=310, offs=4)
*/
ATSstaticdec()
ats_void_type
aux_29 (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
// ATSlocal_void (tmp161) ;
ATSlocal (anairiats_rec_6, tmp162) ;
ATSlocal (ats_ptr_type, tmp163) ;
// ATSlocal_void (tmp164) ;
ATSlocal (ats_bool_type, tmp165) ;
// ATSlocal_void (tmp166) ;
ATSlocal (ats_ptr_type, tmp167) ;
// ATSlocal_void (tmp168) ;
// ATSlocal_void (tmp169) ;
ATSlocal (ats_ptr_type, tmp170) ;
ATSlocal (ats_int_type, tmp171) ;

__ats_lab_aux_29:
do {
/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (arg1 != (ats_sum_ptr_type)0) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
// if (arg1 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_16_1:
tmp162 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_0) ;
tmp163 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_1) ;
tmp165 = atspre_gt_int_int (arg2, 0) ;
if (tmp165) {
/* tmp164 = */ atspre_fprint_string (arg0, ATSstrcst(", ")) ;
} else {
/* empty */
} /* end of [if] */
tmp167 = ats_select_mac(tmp162, atslab_0) ;
/* tmp166 = */ atspre_fprintf_exn (arg0, ATSstrcst("\"%s\""), tmp167) ;
/* tmp168 = */ atspre_fprint_string (arg0, ATSstrcst(": ")) ;
tmp170 = ats_select_mac(tmp162, atslab_1) ;
/* tmp169 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp170) ;
tmp171 = atspre_add_int_int (arg2, 1) ;
arg0 = arg0 ;
arg1 = tmp163 ;
arg2 = tmp171 ;
goto __ats_lab_aux_29 ; // tail call
break ;
} while (0) ;
return /* (tmp161) */ ;
} /* end of [aux_29] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 6190(line=285, offs=3) -- 6676(line=314, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp160) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist:
/* tmp160 = */ aux_29 (arg0, arg1, 0) ;
return /* (tmp160) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__fprint_labjsonvalist] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 6743(line=320, offs=5) -- 6926(line=328, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux0_30 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp172) ;
ATSlocal (ats_ptr_type, tmp173) ;
ATSlocal (ats_ptr_type, tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;

__ats_lab_aux0_30:
tmp173 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp175 = (ats_sum_ptr_type)0 ;
tmp174 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp174)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp174, atslab_0, tmp175) ;
tmp172 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("funclo_name"), tmp173, ATSstrcst("funclo_arglst"), tmp174) ;
return (tmp172) ;
} /* end of [aux0_30] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 6949(line=330, offs=5) -- 7143(line=338, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux1_31 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp176) ;
ATSlocal (ats_ptr_type, tmp177) ;
ATSlocal (ats_ptr_type, tmp178) ;

__ats_lab_aux1_31:
tmp177 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (arg0) ;
tmp178 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_sing (arg1) ;
tmp176 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("funclo_name"), tmp177, ATSstrcst("funclo_arglst"), tmp178) ;
return (tmp176) ;
} /* end of [aux1_31] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7211(line=343, offs=16) -- 7333(line=347, offs=61)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funclo (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp179) ;
ATSlocal (ats_int_type, tmp180) ;
ATSlocal (ats_ptr_type, tmp181) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funclo:
do {
/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp179 = aux0_30 (ATSstrcst("FUNCLOfun")) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_18_1:
tmp180 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_0) ;
tmp181 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (tmp180) ;
tmp179 = aux1_31 (ATSstrcst("FUNCLOclo"), tmp181) ;
break ;
} while (0) ;
return (tmp179) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funclo] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7437(line=355, offs=17) -- 7606(line=360, offs=51)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_caskind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp182) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_caskind:
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp182 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("CK_case")) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_21_0 ; }
__ats_lab_20_1:
tmp182 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("CK_case_pos")) ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
// if (((ats_sum_ptr_type)arg0)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_21_1:
tmp182 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("CK_case_neg")) ;
break ;
} while (0) ;
return (tmp182) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_caskind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 7688(line=366, offs=17) -- 8025(line=379, offs=47)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp183) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funkind:
do {
/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
tmp183 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_fn")) ;
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp183 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_fnx")) ;
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp183 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_fun")) ;
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp183 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_prfn")) ;
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
tmp183 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_prfun")) ;
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (((ats_sum_ptr_type)arg0)->tag != 5) { goto __ats_lab_28_0 ; }
__ats_lab_27_1:
tmp183 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_praxi")) ;
break ;

/* branch: __ats_lab_28 */
__ats_lab_28_0:
// if (((ats_sum_ptr_type)arg0)->tag != 6) { ats_deadcode_failure_handle () ; }
__ats_lab_28_1:
tmp183 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("FK_castfn")) ;
break ;
} while (0) ;
return (tmp183) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_funkind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 8110(line=386, offs=17) -- 8318(line=392, offs=49)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_valkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp184) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_valkind:
do {
/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp184 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("VK_val")) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_31_0 ; }
__ats_lab_30_1:
tmp184 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("VK_prval")) ;
break ;

/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
tmp184 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("VK_val_pos")) ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
// if (((ats_sum_ptr_type)arg0)->tag != 3) { ats_deadcode_failure_handle () ; }
__ats_lab_32_1:
tmp184 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("VK_val_neg")) ;
break ;
} while (0) ;
return (tmp184) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_valkind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 8401(line=398, offs=18) -- 8692(line=407, offs=47)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_dcstkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp185) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_dcstkind:
do {
/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_34_0 ; }
__ats_lab_33_1:
tmp185 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKfun")) ;
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp185 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKval")) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp185 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKpraxi")) ;
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp185 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKprfun")) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
tmp185 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKprval")) ;
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
// if (((ats_sum_ptr_type)arg0)->tag != 5) { ats_deadcode_failure_handle () ; }
__ats_lab_38_1:
tmp185 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("DCKcastfn")) ;
break ;
} while (0) ;
return (tmp185) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_dcstkind] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 8778(line=414, offs=15) -- 8817(line=415, offs=33)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp186) ;
ATSlocal (ats_int_type, tmp187) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp:
tmp187 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stamp_2esats__stamp_get_int (arg0) ;
tmp186 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (tmp187) ;
return (tmp186) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 8871(line=420, offs=16) -- 8917(line=421, offs=39)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp188) ;
ATSlocal (ats_ptr_type, tmp189) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol:
tmp189 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_get_name (arg0) ;
tmp188 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (tmp189) ;
return (tmp188) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 8948(line=423, offs=19) -- 8998(line=424, offs=43)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbolopt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp190) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbolopt:
tmp190 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol) ;
return (tmp190) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbolopt] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 9052(line=429, offs=18) -- 9081(line=429, offs=47)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp191) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location:
tmp191 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_location (arg0) ;
return (tmp191) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_location] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 9110(line=431, offs=18) -- 9139(line=431, offs=47)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_filename (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp192) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_filename:
tmp192 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_filename (arg0) ;
return (tmp192) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_filename] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 9191(line=437, offs=3) -- 9694(line=461, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_label (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp193) ;
ATSlocal (ats_ptr_type, tmp194) ;
ATSlocal (ats_int_type, tmp195) ;
ATSlocal (ats_ptr_type, tmp196) ;
ATSlocal (ats_ptr_type, tmp197) ;
ATSlocal (ats_ptr_type, tmp198) ;
ATSlocal (ats_ptr_type, tmp199) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_label:
tmp194 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_get_int (arg0) ;
do {
/* branch: __ats_lab_39 */
__ats_lab_39_0:
if (tmp194 == (ats_sum_ptr_type)0) { goto __ats_lab_40_0 ; }
__ats_lab_39_1:
tmp195 = ats_caselptrlab_mac(anairiats_sum_9, tmp194, atslab_0) ;
ATS_FREE(tmp194) ;
tmp196 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (tmp195) ;
tmp193 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (ATSstrcst("LABint"), tmp196) ;
break ;

/* branch: __ats_lab_40 */
__ats_lab_40_0:
// if (tmp194 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_40_1:
tmp197 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_get_sym (arg0) ;
do {
/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (tmp197 == (ats_sum_ptr_type)0) { goto __ats_lab_42_0 ; }
__ats_lab_41_1:
tmp198 = ats_caselptrlab_mac(anairiats_sum_8, tmp197, atslab_0) ;
ATS_FREE(tmp197) ;
tmp199 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (tmp198) ;
tmp193 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (ATSstrcst("LABsym"), tmp199) ;
break ;

/* branch: __ats_lab_42 */
__ats_lab_42_0:
// if (tmp197 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_42_1:
tmp193 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONnul_0) ;
break ;
} while (0) ;
break ;
} while (0) ;
return (tmp193) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_label] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 9769(line=466, offs=17) -- 9794(line=466, offs=42)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp200) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored:
tmp200 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONnul_0) ;
return (tmp200) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 52519(line=1874, offs=5) -- 52952(line=1891, offs=4)
*/
ATSstaticdec()
ats_void_type
loop_47 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp205) ;
ATSlocal (ats_ptr_type, tmp206) ;
ATSlocal (ats_ptr_type, tmp207) ;
ATSlocal (ats_ptr_type, tmp208) ;
ATSlocal (ats_ptr_type, tmp209) ;
ATSlocal (ats_ptr_type, tmp210) ;
ATSlocal (ats_ptr_type, tmp211) ;

__ats_lab_loop_47:
do {
/* branch: __ats_lab_43 */
__ats_lab_43_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_44_0 ; }
__ats_lab_43_1:
tmp206 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_0) ;
tmp207 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_1) ;
tmp208 = ((ats_ptr_type(*)(ats_ptr_type, ats_ptr_type))arg1) (tmp206, arg3) ;
tmp209 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp209, atslab_0, tmp208) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp209 ;
// if (ats_ptrget_mac(ats_ptr_type, arg2) == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp210 = &ats_caselptrlab_mac(anairiats_sum_5, ats_ptrget_mac(ats_ptr_type, arg2), atslab_1) ;
arg0 = tmp207 ;
arg1 = arg1 ;
arg2 = tmp210 ;
arg3 = arg3 ;
goto __ats_lab_loop_47 ; // tail call
break ;

/* branch: __ats_lab_44 */
__ats_lab_44_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_44_1:
tmp211 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp211 ;
break ;
} while (0) ;
return /* (tmp205) */ ;
} /* end of [loop_47] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 52444(line=1870, offs=3) -- 53099(line=1899, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_map_funenv_01411_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp204) ;
ATSlocal (ats_ptr_type, tmp212) ;
// ATSlocal_void (tmp213) ;

__ats_lab_list_map_funenv_01411_ats_ptr_type_ats_ptr_type:
/* ats_ptr_type tmp212 ; */
/* tmp213 = */ loop_47 (arg0, arg1, (&tmp212), arg2) ;
tmp204 = tmp212 ;
return (tmp204) ;
} /* end of [list_map_funenv_01411_ats_ptr_type_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 53173(line=1904, offs=3) -- 53424(line=1911, offs=2)
*/
ATSstaticdec()
ats_ptr_type
list_map_fun_01412_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp203) ;

__ats_lab_list_map_fun_01412_ats_ptr_type_ats_ptr_type:
tmp203 = list_map_funenv_01411_ats_ptr_type_ats_ptr_type (arg0, ats_castfn_mac(ats_ptr_type, arg1), atspre_null_ptr) ;
return (tmp203) ;
} /* end of [list_map_fun_01412_ats_ptr_type_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 9851(line=472, offs=7) -- 9947(line=478, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp201) ;
ATSlocal (ats_ptr_type, tmp202) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun:
tmp202 = list_map_fun_01412_ats_ptr_type_ats_ptr_type (arg0, arg1) ;
tmp201 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp201)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_2, tmp201, atslab_0, ats_castfn_mac(ats_ptr_type, tmp202)) ;
return (tmp201) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_list_fun] */

/*
// /home/hwxi/research/Postiats/git/src/pats_jsonize.dats: 10034(line=484, offs=7) -- 10137(line=491, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp214) ;
ATSlocal (ats_ptr_type, tmp215) ;
ATSlocal (ats_ptr_type, tmp216) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun:
do {
/* branch: __ats_lab_45 */
__ats_lab_45_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_46_0 ; }
__ats_lab_45_1:
tmp214 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_none () ;
break ;

/* branch: __ats_lab_46 */
__ats_lab_46_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_46_1:
tmp215 = ats_caselptrlab_mac(anairiats_sum_8, arg0, atslab_0) ;
tmp216 = ((ats_ptr_type(*)(ats_ptr_type))arg1) (tmp215) ;
tmp214 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_some (tmp216) ;
break ;
} while (0) ;
return (tmp214) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_option_fun] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_intinf_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stamp_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_intinf_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stamp_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_filename_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_jsonize_dats.c] */
