/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2014-2-16: 12h:41m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef
struct {
ats_ptr_type atslab_s2exp_srt ;
ats_ptr_type atslab_s2exp_node ;
} anairiats_rec_3 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_5 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_6 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__JSONlist_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2RTBASpre_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2RTBASimp_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2RTBASdef_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2RTbas_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2RTfun_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2RTtup_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Eint_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Eintinf_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Ecst_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Evar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2EVar_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Esizeof_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Eeqeq_13) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Eapp_15) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Emetdec_19) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Einvar_24) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Eerr_30) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_intinf) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rtdat_get_sym) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cst_get_sym) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cst_get_stamp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2var_get_sym) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2var_get_stamp) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2Var_get_stamp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_sym) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_stamp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2rt) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2cst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2Var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp) (ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2explst) (ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp_hnfize) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__jsonize_s2rtbas) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type auxmain_9 (ats_int_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type auxlst_11 (ats_int_type arg0, ats_ptr_type arg1) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 1999(line=79, offs=3) -- 2228(line=88, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2rt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2rt:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp1 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__jsonize_s2rtbas (tmp1) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("s2rt_fun")) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("s2rt_tup")) ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
__ats_lab_3_1:
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_string (ATSstrcst("s2rt_anon")) ;
break ;
} while (0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2rt] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 2306(line=94, offs=3) -- 2553(line=104, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__jsonize_s2rtbas (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__jsonize_s2rtbas:
do {
/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp3 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp2 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (tmp3) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp4 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
tmp2 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (tmp4) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
// if (((ats_sum_ptr_type)arg0)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_6_1:
tmp5 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp6 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rtdat_get_sym (tmp5) ;
tmp2 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (tmp6) ;
break ;
} while (0) ;
return (tmp2) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__jsonize_s2rtbas] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 2630(line=110, offs=3) -- 2821(line=122, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2cst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_int_type, tmp11) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2cst:
tmp9 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cst_get_sym (arg0) ;
tmp8 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (tmp9) ;
tmp11 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cst_get_stamp (arg0) ;
tmp10 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp (tmp11) ;
tmp7 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("s2cst_name"), tmp8, ATSstrcst("s2cst_stamp"), tmp10) ;
return (tmp7) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2cst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 2896(line=128, offs=3) -- 3087(line=140, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2var (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_int_type, tmp16) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2var:
tmp14 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2var_get_sym (arg0) ;
tmp13 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (tmp14) ;
tmp16 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2var_get_stamp (arg0) ;
tmp15 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp (tmp16) ;
tmp12 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("s2var_name"), tmp13, ATSstrcst("s2var_stamp"), tmp15) ;
return (tmp12) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2var] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 3162(line=146, offs=3) -- 3285(line=155, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2Var (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_int_type, tmp19) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2Var:
tmp19 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2Var_get_stamp (arg0) ;
tmp18 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp (tmp19) ;
tmp17 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval1 (ATSstrcst("s2Var_stamp"), tmp18) ;
return (tmp17) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2Var] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 3360(line=161, offs=3) -- 3551(line=173, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_d2con (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_int_type, tmp24) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_d2con:
tmp22 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_sym (arg0) ;
tmp21 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_symbol (tmp22) ;
tmp24 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_stamp (arg0) ;
tmp23 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_stamp (tmp24) ;
tmp20 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("d2con_name"), tmp21, ATSstrcst("d2con_stamp"), tmp23) ;
return (tmp20) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_d2con] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 3630(line=179, offs=3) -- 3667(line=179, offs=40)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize0_s2exp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp25) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize0_s2exp:
tmp25 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (0, arg0) ;
return (tmp25) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize0_s2exp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 3695(line=182, offs=3) -- 3732(line=182, offs=40)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize1_s2exp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp26) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize1_s2exp:
tmp26 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (1, arg0) ;
return (tmp26) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize1_s2exp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 3810(line=190, offs=5) -- 5297(line=251, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxmain_9 (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_bool_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_int_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;

__ats_lab_auxmain_9:
tmp30 = atspre_eq_int_int (arg0, 0) ;
if (tmp30) {
tmp29 = arg1 ;
} else {
tmp29 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp_hnfize (arg1) ;
} /* end of [if] */
tmp31 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_3, tmp29), atslab_s2exp_node) ;
do {
/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp31)->tag != 0) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp32 = ats_caselptrlab_mac(anairiats_sum_4, tmp31, atslab_0) ;
tmp33 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_int (tmp32) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S2Eint"), tmp33) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp31)->tag != 1) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp34 = ats_caselptrlab_mac(anairiats_sum_1, tmp31, atslab_0) ;
tmp35 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_intinf (tmp34) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S2Eintinf"), tmp35) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp31)->tag != 2) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp36 = ats_caselptrlab_mac(anairiats_sum_1, tmp31, atslab_0) ;
tmp37 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2cst (tmp36) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S2Ecst"), tmp37) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp31)->tag != 5) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp38 = ats_caselptrlab_mac(anairiats_sum_1, tmp31, atslab_0) ;
tmp39 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2var (tmp38) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S2Evar"), tmp39) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp31)->tag != 6) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp40 = ats_caselptrlab_mac(anairiats_sum_1, tmp31, atslab_0) ;
tmp41 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2Var (tmp40) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S2EVar"), tmp41) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)tmp31)->tag != 11) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp42 = ats_caselptrlab_mac(anairiats_sum_1, tmp31, atslab_0) ;
tmp43 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (arg0, tmp42) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S2Esizeof"), tmp43) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)tmp31)->tag != 13) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp44 = ats_caselptrlab_mac(anairiats_sum_5, tmp31, atslab_0) ;
tmp45 = ats_caselptrlab_mac(anairiats_sum_5, tmp31, atslab_1) ;
tmp46 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (arg0, tmp44) ;
tmp47 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (arg0, tmp45) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("S2Eeqeq"), tmp46, tmp47) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp31)->tag != 15) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp48 = ats_caselptrlab_mac(anairiats_sum_5, tmp31, atslab_0) ;
tmp49 = ats_caselptrlab_mac(anairiats_sum_5, tmp31, atslab_1) ;
tmp50 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (arg0, tmp48) ;
tmp51 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2explst (arg0, tmp49) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("S2Eapp"), tmp50, tmp51) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)tmp31)->tag != 19) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp52 = ats_caselptrlab_mac(anairiats_sum_5, tmp31, atslab_0) ;
tmp53 = ats_caselptrlab_mac(anairiats_sum_5, tmp31, atslab_1) ;
tmp54 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2explst (arg0, tmp52) ;
tmp55 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2explst (arg0, tmp53) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("S2Emetdec"), tmp54, tmp55) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp31)->tag != 24) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp56 = ats_caselptrlab_mac(anairiats_sum_1, tmp31, atslab_0) ;
tmp57 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (arg0, tmp56) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S2Einvar"), tmp57) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)tmp31)->tag != 30) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0 (ATSstrcst("S2Eerr")) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
__ats_lab_18_1:
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_conarg0 (ATSstrcst("S2Eignored")) ;
break ;
} while (0) ;
return (tmp28) ;
} /* end of [auxmain_9] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 3784(line=188, offs=3) -- 5477(line=259, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp:
tmp58 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_3, arg1), atslab_s2exp_srt) ;
tmp59 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2rt (tmp58) ;
tmp60 = auxmain_9 (arg0, arg1) ;
tmp27 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("s2exp_srt"), tmp59, ATSstrcst("s2exp_node"), tmp60) ;
return (tmp27) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 5581(line=267, offs=5) -- 5812(line=278, offs=37)
*/
ATSstaticdec()
ats_ptr_type
auxlst_11 (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;

__ats_lab_auxlst_11:
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp63 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_0) ;
tmp64 = ats_caselptrlab_mac(anairiats_sum_6, arg1, atslab_1) ;
tmp65 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2exp (arg0, tmp63) ;
tmp66 = auxlst_11 (arg0, tmp64) ;
tmp62 = ATS_MALLOC(sizeof(anairiats_sum_6)) ;
ats_selptrset_mac(anairiats_sum_6, tmp62, atslab_0, tmp65) ;
ats_selptrset_mac(anairiats_sum_6, tmp62, atslab_1, tmp66) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_20_1:
tmp62 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp62) ;
} /* end of [auxlst_11] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 5555(line=265, offs=3) -- 5855(line=282, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2explst (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp67) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2explst:
tmp67 = auxlst_11 (arg0, arg1) ;
tmp61 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp61)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_1, tmp61, atslab_0, tmp67) ;
return (tmp61) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2explst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_staexp2_jsonize.dats: 5931(line=287, offs=15) -- 5961(line=287, offs=45)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2eff (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp68) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2eff:
tmp68 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__jsonize_ignored (arg0) ;
return (tmp68) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__jsonize_s2eff] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_lexing_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e11_2prelude_2SATS_2unsafe_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_jsonize_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_lexing_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_jsonize_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_staexp2_jsonize_dats.c] */
