/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2015-9-22: 17h:58m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} anairiats_sum_5 ;

typedef
struct {
ats_ptr_type atslab_c3nstroptref_loc ;
ats_ptr_type atslab_c3nstroptref_ref ;
} anairiats_rec_6 ;

typedef
struct {
ats_ptr_type atslab_h3ypo_loc ;
ats_ptr_type atslab_h3ypo_node ;
} anairiats_rec_7 ;

typedef
struct {
ats_ptr_type atslab_c3nstr_loc ;
ats_ptr_type atslab_c3nstr_kind ;
ats_ptr_type atslab_c3nstr_node ;
} anairiats_rec_8 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_9 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e12_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2RTBASpre_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2RTBASimp_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2RTBASdef_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2RTbas_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2RTfun_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2RTtup_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2RTVar_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__S2RTerr_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKmain_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKcase_exhaustiveness_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKtermet_isnat_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKtermet_isdec_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKsome_fin_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKsome_lvar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKsome_vbox_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKlstate_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKlstate_var_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKloop_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3TKsolverify_10) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__H3YPOprop_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__H3YPObind_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__H3YPOeqeq_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3NSTRprop_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3NSTRitmlst_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__C3NSTRsolverify_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__S3ITMsvar_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__S3ITMhypo_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__S3ITMsVar_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__S3ITMcnstr_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__S3ITMcnstr_ref_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__S3ITMdisj_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__S3ITMsolassert_6) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_newline) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_int) (ats_int_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_labval2) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_labval3) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg0) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg2) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg3) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__fprint_jsonval) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_caskind) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_location) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_ignored) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_list_fun) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_option_fun) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rtdatset_nil) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rtdatset_add) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rtdatset_listize) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2cst_get_srt) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2cstset_vt_listize_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2var_get_srt) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2varset_vt_listize_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2cst_long) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2rtdat_long) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2var_long) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2Var) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_d2var) (ats_ptr_type) ;
ATSextern_fun(anairiats_rec_1, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__c3nstr_mapgen_scst_svar) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__jsonize_c3nstr) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type auxmain_5 (ats_ptr_type arg0) ;
static
ats_ptr_type auxmain_7 (ats_ptr_type arg0) ;
static
ats_ptr_type aux_s2rt_9 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_s2rtlst_10 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_s2rtbas_11 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_s2cst_12 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_s2cstlst_13 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_s2var_14 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_s2varlst_15 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type c3nstr_get_s2rtdatlst_16 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_19 (ats_ptr_type arg0) ;
static
ats_void_type list_vt_free_01499_ats_ptr_type (ats_ptr_type arg0) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 2175(line=92, offs=20) -- 3735(line=152, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_int_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg0 (ATSstrcst("C3TKmain")) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp1 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp2 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
tmp3 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_caskind (tmp1) ;
tmp4 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_ignored (tmp2) ;
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("C3TKcase_exhaustiveness"), tmp3, tmp4) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg0 (ATSstrcst("C3TKtermet_isnat")) ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg0 (ATSstrcst("C3TKtermet_isdec")) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp5 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp6 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp7 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_2) ;
tmp8 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_d2var (tmp5) ;
tmp9 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp6) ;
tmp10 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp7) ;
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg3 (ATSstrcst("C3TKsome_fin"), tmp8, tmp9, tmp10) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)arg0)->tag != 5) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp11 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp12 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp13 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_2) ;
tmp14 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_d2var (tmp11) ;
tmp15 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp12) ;
tmp16 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp13) ;
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg3 (ATSstrcst("C3TKsome_lvar"), tmp14, tmp15, tmp16) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)arg0)->tag != 6) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp17 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_0) ;
tmp18 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_1) ;
tmp19 = ats_caselptrlab_mac(anairiats_sum_3, arg0, atslab_2) ;
tmp20 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_d2var (tmp17) ;
tmp21 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp18) ;
tmp22 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp19) ;
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg3 (ATSstrcst("C3TKsome_vbox"), tmp20, tmp21, tmp22) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)arg0)->tag != 7) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg0 (ATSstrcst("C3TKlstate")) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)arg0)->tag != 8) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp23 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp24 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_d2var (tmp23) ;
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("C3TKlstate_var"), tmp24) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)arg0)->tag != 9) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp25 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_0) ;
tmp26 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_int (tmp25) ;
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("C3TKloop"), tmp26) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
// if (((ats_sum_ptr_type)arg0)->tag != 10) { ats_deadcode_failure_handle () ; }
__ats_lab_10_1:
tmp0 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg0 (ATSstrcst("C3TKsolverify")) ;
break ;
} while (0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 4125(line=172, offs=3) -- 5076(line=210, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm:
do {
/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp28 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp29 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2var (tmp28) ;
tmp27 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMsvar"), tmp29) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp30 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp31 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo (tmp30) ;
tmp27 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMhypo"), tmp31) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp32 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp33 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2Var (tmp32) ;
tmp27 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMsVar"), tmp33) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp34 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp35 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__jsonize_c3nstr (tmp34) ;
tmp27 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMcnstr"), tmp35) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)arg0)->tag != 4) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp36 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp37 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, tmp36), atslab_c3nstroptref_loc) ;
tmp38 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_6, tmp36), atslab_c3nstroptref_ref) ;
tmp39 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_location (tmp37) ;
tmp41 = ats_ptrget_mac(ats_ptr_type, tmp38) ;
tmp40 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt (tmp41) ;
tmp27 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("S3ITMcnstr_ref"), tmp39, tmp40) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)arg0)->tag != 5) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp42 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp43 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst (tmp42) ;
tmp27 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMdisj"), tmp43) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
// if (((ats_sum_ptr_type)arg0)->tag != 6) { ats_deadcode_failure_handle () ; }
__ats_lab_17_1:
tmp44 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp45 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp44) ;
tmp27 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("S3ITMsolassert"), tmp45) ;
break ;
} while (0) ;
return (tmp27) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 5156(line=216, offs=3) -- 5203(line=216, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp46) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst:
tmp46 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_list_fun (arg0, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itm) ;
return (tmp46) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 5236(line=219, offs=3) -- 5288(line=219, offs=55)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp47) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst:
tmp47 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_list_fun (arg0, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst) ;
return (tmp47) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlstlst] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 5359(line=227, offs=5) -- 6215(line=265, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxmain_5 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;

__ats_lab_auxmain_5:
tmp50 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_7, arg0), atslab_h3ypo_node) ;
do {
/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (((ats_sum_ptr_type)tmp50)->tag != 0) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp51 = ats_caselptrlab_mac(anairiats_sum_4, tmp50, atslab_0) ;
tmp52 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp51) ;
tmp49 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("H3YPOprop"), tmp52) ;
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)tmp50)->tag != 1) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp53 = ats_caselptrlab_mac(anairiats_sum_2, tmp50, atslab_0) ;
tmp54 = ats_caselptrlab_mac(anairiats_sum_2, tmp50, atslab_1) ;
tmp55 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2var (tmp53) ;
tmp56 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp54) ;
tmp49 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("H3YPObind"), tmp55, tmp56) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
// if (((ats_sum_ptr_type)tmp50)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_20_1:
tmp57 = ats_caselptrlab_mac(anairiats_sum_2, tmp50, atslab_0) ;
tmp58 = ats_caselptrlab_mac(anairiats_sum_2, tmp50, atslab_1) ;
tmp59 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp57) ;
tmp60 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp58) ;
tmp49 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg2 (ATSstrcst("H3YPOeqeq"), tmp59, tmp60) ;
break ;
} while (0) ;
return (tmp49) ;
} /* end of [auxmain_5] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 5339(line=225, offs=3) -- 6388(line=273, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo:
tmp61 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_7, arg0), atslab_h3ypo_loc) ;
tmp62 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_location (tmp61) ;
tmp63 = auxmain_5 (arg0) ;
tmp48 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_labval2 (ATSstrcst("h3ypo_loc"), tmp62, ATSstrcst("h3ypo_node"), tmp63) ;
return (tmp48) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_h3ypo] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 6484(line=281, offs=5) -- 6914(line=300, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxmain_7 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;

__ats_lab_auxmain_7:
tmp66 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, arg0), atslab_c3nstr_node) ;
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (((ats_sum_ptr_type)tmp66)->tag != 0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
tmp67 = ats_caselptrlab_mac(anairiats_sum_4, tmp66, atslab_0) ;
tmp68 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp67) ;
tmp65 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("C3NSTRprop"), tmp68) ;
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)tmp66)->tag != 1) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
tmp69 = ats_caselptrlab_mac(anairiats_sum_4, tmp66, atslab_0) ;
tmp70 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_s3itmlst (tmp69) ;
tmp65 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("C3NSTRitmlst"), tmp70) ;
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
// if (((ats_sum_ptr_type)tmp66)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_23_1:
tmp71 = ats_caselptrlab_mac(anairiats_sum_4, tmp66, atslab_0) ;
tmp72 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize1_s2exp (tmp71) ;
tmp65 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_conarg1 (ATSstrcst("C3NSTRsolverify"), tmp72) ;
break ;
} while (0) ;
return (tmp65) ;
} /* end of [auxmain_7] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 6464(line=279, offs=3) -- 7171(line=314, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__jsonize_c3nstr (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__jsonize_c3nstr:
tmp73 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, arg0), atslab_c3nstr_loc) ;
tmp74 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_location (tmp73) ;
tmp76 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, arg0), atslab_c3nstr_kind) ;
tmp75 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstrkind (tmp76) ;
tmp77 = auxmain_7 (arg0) ;
tmp64 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonval_labval3 (ATSstrcst("c3nstr_loc"), tmp74, ATSstrcst("c3nstr_kind"), tmp75, ATSstrcst("c3nstr_node"), tmp77) ;
return (tmp64) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__jsonize_c3nstr] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 7251(line=320, offs=3) -- 7299(line=320, offs=51)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp78) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt:
tmp78 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_option_fun (arg0, &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__jsonize_c3nstr) ;
return (tmp78) ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__jsonize_c3nstropt] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 7395(line=330, offs=1) -- 7695(line=343, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_s2rt_9 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;

__ats_lab_aux_s2rt_9:
do {
/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp80 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp79 = aux_s2rtbas_11 (tmp80, arg1) ;
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp81 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp82 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
tmp83 = aux_s2rtlst_10 (tmp81, arg1) ;
arg0 = tmp82 ;
arg1 = tmp83 ;
goto __ats_lab_aux_s2rt_9 ; // tail call
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)arg0)->tag != 2) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
tmp84 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp79 = aux_s2rtlst_10 (tmp84, arg1) ;
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (((ats_sum_ptr_type)arg0)->tag != 3) { goto __ats_lab_28_0 ; }
__ats_lab_27_1:
tmp79 = arg1 ;
break ;

/* branch: __ats_lab_28 */
__ats_lab_28_0:
// if (((ats_sum_ptr_type)arg0)->tag != 4) { ats_deadcode_failure_handle () ; }
__ats_lab_28_1:
tmp79 = arg1 ;
break ;
} while (0) ;
return (tmp79) ;
} /* end of [aux_s2rt_9] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 7703(line=346, offs=1) -- 7911(line=356, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_s2rtlst_10 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;

__ats_lab_aux_s2rtlst_10:
do {
/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp85 = arg1 ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_30_1:
tmp86 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_0) ;
tmp87 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_1) ;
tmp88 = aux_s2rt_9 (tmp86, arg1) ;
arg0 = tmp87 ;
arg1 = tmp88 ;
goto __ats_lab_aux_s2rtlst_10 ; // tail call
break ;
} while (0) ;
return (tmp85) ;
} /* end of [aux_s2rtlst_10] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 7919(line=359, offs=1) -- 8082(line=368, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_s2rtbas_11 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;

__ats_lab_aux_s2rtbas_11:
do {
/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
tmp89 = arg1 ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
tmp89 = arg1 ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
// if (((ats_sum_ptr_type)arg0)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_33_1:
tmp90 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp89 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rtdatset_add (arg1, tmp90) ;
break ;
} while (0) ;
return (tmp89) ;
} /* end of [aux_s2rtbas_11] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 8090(line=371, offs=1) -- 8172(line=374, offs=46)
*/
ATSstaticdec()
ats_ptr_type
aux_s2cst_12 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;

__ats_lab_aux_s2cst_12:
tmp92 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2cst_get_srt (arg0) ;
tmp91 = aux_s2rt_9 (tmp92, arg1) ;
return (tmp91) ;
} /* end of [aux_s2cst_12] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 8177(line=376, offs=1) -- 8364(line=386, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_s2cstlst_13 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp96) ;

__ats_lab_aux_s2cstlst_13:
do {
/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp93 = arg1 ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_35_1:
tmp94 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_0) ;
tmp95 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_1) ;
tmp96 = aux_s2cst_12 (tmp94, arg1) ;
arg0 = tmp95 ;
arg1 = tmp96 ;
goto __ats_lab_aux_s2cstlst_13 ; // tail call
break ;
} while (0) ;
return (tmp93) ;
} /* end of [aux_s2cstlst_13] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 8372(line=389, offs=1) -- 8454(line=392, offs=46)
*/
ATSstaticdec()
ats_ptr_type
aux_s2var_14 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;

__ats_lab_aux_s2var_14:
tmp98 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2var_get_srt (arg0) ;
tmp97 = aux_s2rt_9 (tmp98, arg1) ;
return (tmp97) ;
} /* end of [aux_s2var_14] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 8459(line=394, offs=1) -- 8646(line=404, offs=2)
*/
ATSstaticdec()
ats_ptr_type
aux_s2varlst_15 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_ptr_type, tmp102) ;

__ats_lab_aux_s2varlst_15:
do {
/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp99 = arg1 ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
// if (arg0 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_37_1:
tmp100 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_0) ;
tmp101 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_1) ;
tmp102 = aux_s2var_14 (tmp100, arg1) ;
arg0 = tmp101 ;
arg1 = tmp102 ;
goto __ats_lab_aux_s2varlst_15 ; // tail call
break ;
} while (0) ;
return (tmp99) ;
} /* end of [aux_s2varlst_15] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 8676(line=409, offs=1) -- 8893(line=418, offs=4)
*/
ATSstaticdec()
ats_ptr_type
c3nstr_get_s2rtdatlst_16 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;

__ats_lab_c3nstr_get_s2rtdatlst_16:
tmp104 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rtdatset_nil () ;
tmp105 = aux_s2cstlst_13 (arg0, tmp104) ;
tmp106 = aux_s2varlst_15 (arg1, tmp105) ;
tmp103 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2rtdatset_listize (tmp106) ;
return (tmp103) ;
} /* end of [c3nstr_get_s2rtdatlst_16] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 4893(line=177, offs=7) -- 5015(line=178, offs=73)
*/
ATSstaticdec()
ats_void_type
loop_19 (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;

__ats_lab_loop_19:
do {
/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp120 = ats_caselptrlab_mac(anairiats_sum_9, arg0, atslab_1) ;
ATS_FREE(arg0) ;
arg0 = tmp120 ;
goto __ats_lab_loop_19 ; // tail call
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_39_1:
break ;
} while (0) ;
return /* (tmp119) */ ;
} /* end of [loop_19] */

/*
// /home/hwxi/Research/ATS-Anairiats/prelude/DATS/list_vt.dats: 4875(line=176, offs=14) -- 5054(line=182, offs=4)
*/
ATSstaticdec()
ats_void_type
list_vt_free_01499_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp118) ;

__ats_lab_list_vt_free_01499_ats_ptr_type:
/* tmp118 = */ loop_19 (arg0) ;
return /* (tmp118) */ ;
} /* end of [list_vt_free_01499_ats_ptr_type] */

/*
// /home/hwxi/Research/ATS-Postiats/src/pats_constraint3_jsonize.dats: 8999(line=426, offs=3) -- 10284(line=485, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__c3nstr_export (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp107) ;
ATSlocal (anairiats_rec_1, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;
ATSlocal (ats_ptr_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;
ATSlocal (ats_ptr_type, tmp116) ;
// ATSlocal_void (tmp117) ;
// ATSlocal_void (tmp121) ;
// ATSlocal_void (tmp122) ;
ATSlocal (ats_ptr_type, tmp123) ;
// ATSlocal_void (tmp124) ;
// ATSlocal_void (tmp125) ;
// ATSlocal_void (tmp126) ;
// ATSlocal_void (tmp127) ;
// ATSlocal_void (tmp128) ;
// ATSlocal_void (tmp129) ;
// ATSlocal_void (tmp130) ;
// ATSlocal_void (tmp131) ;
// ATSlocal_void (tmp132) ;
// ATSlocal_void (tmp133) ;
// ATSlocal_void (tmp134) ;
// ATSlocal_void (tmp135) ;

__ats_lab__2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__c3nstr_export:
tmp108 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__c3nstr_mapgen_scst_svar (arg1) ;
tmp109 = ats_select_mac(tmp108, atslab_0) ;
tmp110 = ats_select_mac(tmp108, atslab_1) ;
tmp111 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2cstset_vt_listize_free (tmp109) ;
tmp112 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__s2varset_vt_listize_free (tmp110) ;
tmp113 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_list_fun (ats_castfn_mac(ats_ptr_type, tmp111), &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2cst_long) ;
tmp114 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_list_fun (ats_castfn_mac(ats_ptr_type, tmp112), &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2var_long) ;
tmp115 = c3nstr_get_s2rtdatlst_16 (ats_castfn_mac(ats_ptr_type, tmp111), ats_castfn_mac(ats_ptr_type, tmp112)) ;
tmp116 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__jsonize_list_fun (ats_castfn_mac(ats_ptr_type, tmp115), &_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__jsonize_s2rtdat_long) ;
/* tmp117 = */ list_vt_free_01499_ats_ptr_type (tmp111) ;
/* tmp121 = */ list_vt_free_01499_ats_ptr_type (tmp112) ;
/* tmp122 = */ list_vt_free_01499_ats_ptr_type (tmp115) ;
tmp123 = _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__jsonize_c3nstr (arg1) ;
/* tmp124 = */ atspre_fprint_string (arg0, ATSstrcst("{\n\"s2cstmap\":\n")) ;
/* tmp125 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp113) ;
/* tmp126 = */ atspre_fprint_newline (arg0) ;
/* tmp127 = */ atspre_fprint_string (arg0, ATSstrcst(",\n\"s2varmap\":\n")) ;
/* tmp128 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp114) ;
/* tmp129 = */ atspre_fprint_newline (arg0) ;
/* tmp130 = */ atspre_fprint_string (arg0, ATSstrcst(",\n\"s2rtdatmap\":\n")) ;
/* tmp131 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp116) ;
/* tmp132 = */ atspre_fprint_newline (arg0) ;
/* tmp133 = */ atspre_fprint_string (arg0, ATSstrcst(",\n\"c3nstrbody\":\n")) ;
/* tmp134 = */ _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__fprint_jsonval (arg0, tmp123) ;
/* tmp135 = */ atspre_fprint_string (arg0, ATSstrcst("\n}")) ;
/* tmp107 = */ atspre_fprint_newline (arg0) ;
return /* (tmp107) */ ;
} /* end of [_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__c3nstr_export] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__staload () {
static int _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__staload_flag) return ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__staload_flag = 1 ;

// _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e12_2prelude_2SATS_2unsafe_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_dynexp2_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_jsonize_synent2_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_trans3_env_2esats__staload () ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__dynload () {
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__dynload_flag = 1 ;
_2home_2hwxi_2Research_2ATS_2dPostiats_2src_2pats_constraint3_jsonize_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e12_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_constraint3_jsonize_dats.c] */
