/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2014-8-29: 11h:29m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_d2exp_loc ;
ats_ptr_type atslab_d2exp_node ;
ats_ptr_type atslab_d2exp_type ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_3 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_4 ;

typedef
struct {
ats_ptr_type atslab_p1at_loc ;
ats_ptr_type atslab_p1at_node ;
} anairiats_rec_5 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_6 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_7 ;

typedef
struct {
ats_ptr_type atslab_d1exp_loc ;
ats_ptr_type atslab_d1exp_node ;
} anairiats_rec_8 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_9 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_10 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_11 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e11_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__P1Tlist_14) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_dyn_47) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_met_49) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_sta_ana_50) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__D1Elam_sta_syn_51) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Evar_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eint_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ebool_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Echar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Estring_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ei0nt_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ec0har_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Es0tring_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Etop_12) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eselab_35) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eviewat_37) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Ederef_38) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Earrsub_41) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Eexist_48) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_dyn_49) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2Elam_sta_52) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALderef_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALvar_lin_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALvar_mut_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALarrsub_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALviewat_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__D2LVALnone_5) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_arity_full) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_get_artylst) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_linear) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst) (ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_int_type loop_3 (ats_ptr_type arg0, ats_int_type arg1) ;
static
ats_int_type list_length_01409_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_bool_type __ats_fun_4 (ats_int_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type __ats_fun_4_closure_make (ats_int_type env0) ;
static
ats_bool_type __ats_fun_4_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_bool_type app_6 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_8 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type list_filter_funenv_01337_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type list_filter_vclo_01339_ats_ptr_type (ats_ptr_type arg0, ats_ref_type arg1) ;
static
ats_int_type p1at_arity_9 (ats_ptr_type arg0) ;
static
ats_bool_type loop1_11 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type loop2_12 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static
ats_bool_type loop1_11_0loop2_12 (ats_int_type arg0, ...) ;
static
ats_bool_type aritest_10 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type d2exp_d2var_lvalize_15 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 1758(line=61, offs=3) -- 2209(line=89, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_bool_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst:
tmp1 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp1)->tag != 1) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp2 = ats_caselptrlab_mac(anairiats_sum_2, tmp1, atslab_0) ;
tmp3 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl (tmp2) ;
if (tmp3) {
tmp0 = ats_false_bool ;
} else {
tmp0 = ats_true_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)tmp1)->tag != 49) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp1)->tag != 52) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp1)->tag != 2) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp1)->tag != 4) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp1)->tag != 5) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp1)->tag != 7) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp1)->tag != 8) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp1)->tag != 9) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp1)->tag != 11) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp1)->tag != 12) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp0 = ats_true_bool ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp1)->tag != 48) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp4 = ats_caselptrlab_mac(anairiats_sum_3, tmp1, atslab_1) ;
arg0 = tmp4 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst ; // tail call
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
__ats_lab_12_1:
tmp0 = ats_false_bool ;
break ;
} while (0) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_is_varlamcst] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51781(line=1842, offs=7) -- 51921(line=1845, offs=6)
*/
ATSstaticdec()
ats_int_type
loop_3 (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_int_type, tmp10) ;

__ats_lab_loop_3:
do {
/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp9 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp10 = atspre_isucc (arg1) ;
arg0 = tmp9 ;
arg1 = tmp10 ;
goto __ats_lab_loop_3 ; // tail call
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_14_1:
tmp8 = arg1 ;
break ;
} while (0) ;
return (tmp8) ;
} /* end of [loop_3] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 51764(line=1841, offs=13) -- 52005(line=1849, offs=4)
*/
ATSstaticdec()
ats_int_type
list_length_01409_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp7) ;

__ats_lab_list_length_01409_ats_ptr_type:
tmp7 = loop_3 (arg0, 0) ;
return (tmp7) ;
} /* end of [list_length_01409_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2388(line=99, offs=18) -- 2477(line=101, offs=52)
*/
ATSstaticdec()
ats_bool_type
__ats_fun_4 (ats_int_type env0, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp13) ;
ATSlocal (ats_int_type, tmp14) ;

__ats_lab___ats_fun_4:
tmp14 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__d2con_get_arity_full (arg0) ;
tmp13 = atspre_eq_int_int (tmp14, env0) ;
return (tmp13) ;
} /* end of [__ats_fun_4] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
} __ats_fun_4_closure_type ;

ats_bool_type
__ats_fun_4_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return __ats_fun_4 (((__ats_fun_4_closure_type*)cloptr)->closure_env_0, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
__ats_fun_4_closure_init (__ats_fun_4_closure_type *p_clo, ats_int_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&__ats_fun_4_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 21113(line=764, offs=6) -- 21259(line=768, offs=6)
*/
ATSstaticdec()
ats_bool_type
app_6 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp18) ;

__ats_lab_app_6:
tmp18 = ((ats_bool_type(*)(ats_clo_ptr_type, ats_ptr_type))(ats_closure_fun(arg1))) (arg1, arg0) ;
return (tmp18) ;
} /* end of [app_6] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 19833(line=716, offs=7) -- 20397(line=733, offs=40)
*/
ATSstaticdec()
ats_void_type
loop_8 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_bool_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;

__ats_lab_loop_8:
do {
/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp21 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp22 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp23 = ((ats_bool_type(*)(ats_ptr_type, ats_ptr_type))arg1) (tmp21, arg3) ;
if (tmp23) {
tmp24 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
ats_selptrset_mac(anairiats_sum_4, tmp24, atslab_0, tmp21) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp24 ;
// if (ats_ptrget_mac(ats_ptr_type, arg2) == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp25 = &ats_caselptrlab_mac(anairiats_sum_4, ats_ptrget_mac(ats_ptr_type, arg2), atslab_1) ;
arg0 = tmp22 ;
arg1 = arg1 ;
arg2 = tmp25 ;
arg3 = arg3 ;
goto __ats_lab_loop_8 ; // tail call
} else {
arg0 = tmp22 ;
arg1 = arg1 ;
arg2 = arg2 ;
arg3 = arg3 ;
goto __ats_lab_loop_8 ; // tail call
} /* end of [if] */
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_16_1:
tmp26 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp26 ;
break ;
} while (0) ;
return /* (tmp20) */ ;
} /* end of [loop_8] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 19800(line=714, offs=24) -- 20566(line=744, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_filter_funenv_01337_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp27) ;
// ATSlocal_void (tmp28) ;

__ats_lab_list_filter_funenv_01337_ats_ptr_type:
/* ats_ptr_type tmp27 ; */
/* tmp28 = */ loop_8 (arg0, arg1, (&tmp27), arg2) ;
tmp19 = tmp27 ;
return (tmp19) ;
} /* end of [list_filter_funenv_01337_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 20978(line=760, offs=19) -- 21434(line=775, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_filter_vclo_01339_ats_ptr_type (ats_ptr_type arg0, ats_ref_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp17) ;

__ats_lab_list_filter_vclo_01339_ats_ptr_type:
tmp17 = list_filter_funenv_01337_ats_ptr_type (arg0, &app_6, arg1) ;
return (tmp17) ;
} /* end of [list_filter_vclo_01339_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2294(line=95, offs=3) -- 2721(line=109, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_int_type, tmp6) ;
ATSlocal (ats_bool_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (__ats_fun_4_closure_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity:
tmp6 = list_length_01409_ats_ptr_type (arg0) ;
tmp11 = atspre_igte (tmp6, 2) ;
if (tmp11) {
/* ats_ptr_type tmp12 ; */
tmp12 = &(tmp15) ;
__ats_fun_4_closure_init (tmp12, arg1) ; // closure initialization
tmp16 = list_filter_vclo_01339_ats_ptr_type (arg0, tmp12) ;
do {
/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (ats_castfn_mac(ats_ptr_type, tmp16) == (ats_sum_ptr_type)0) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp5 = ats_castfn_mac(ats_ptr_type, tmp16) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
// if (ats_castfn_mac(ats_ptr_type, tmp16) != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_18_1:
tmp5 = arg0 ;
break ;
} while (0) ;
} else {
tmp5 = arg0 ;
} /* end of [if] */
return (tmp5) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2con_select_arity] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2814(line=117, offs=4) -- 2923(line=119, offs=55)
*/
ATSstaticdec()
ats_int_type
p1at_arity_9 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;

__ats_lab_p1at_arity_9:
tmp30 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_5, arg0), atslab_p1at_node) ;
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (((ats_sum_ptr_type)tmp30)->tag != 14) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp31 = ats_caselptrlab_mac(anairiats_sum_6, tmp30, atslab_1) ;
tmp29 = list_length_01409_ats_ptr_type (tmp31) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
__ats_lab_20_1:
tmp29 = 1 ;
break ;
} while (0) ;
return (tmp29) ;
} /* end of [p1at_arity_9] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3004(line=124, offs=7) -- 3126(line=126, offs=68)
*/
ATSstaticdec()
ats_bool_type
loop1_11 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp51) ;

tmp51 = loop1_11_0loop2_12 (0, arg0, arg1) ;
return (tmp51) ;
} /* end of [loop1_11] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3133(line=127, offs=7) -- 3490(line=134, offs=17)
*/
ATSstaticdec()
ats_bool_type
loop2_12 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_bool_type, tmp52) ;

tmp52 = loop1_11_0loop2_12 (1, arg0, arg1, arg2) ;
return (tmp52) ;
} /* end of [loop2_12] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3004(line=124, offs=7) -- 3490(line=134, offs=17)
*/
ATSstaticdec()
ats_bool_type
loop1_11_0loop2_12 (ats_int_type arg0, ...) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_int_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_bool_type, tmp38) ;
ATSlocal (ats_int_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_bool_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_bool_type, tmp45) ;
ATSlocal (ats_int_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_bool_type, tmp50) ;

va_list funarg ;

switch (arg0) {
case 0:
va_start(funarg, arg0) ;
tmp33 = va_arg(funarg, ats_ptr_type) ;
tmp34 = va_arg(funarg, ats_ptr_type) ;
va_end(funarg) ;
goto __ats_lab_loop1_11 ;

case 1:
va_start(funarg, arg0) ;
tmp35 = va_arg(funarg, ats_ptr_type) ;
tmp36 = va_arg(funarg, ats_int_type) ;
tmp37 = va_arg(funarg, ats_ptr_type) ;
va_end(funarg) ;
goto __ats_lab_loop2_12 ;

default: exit(1) ; /* deadcode */
} /* end of switch */

ATSlocal (va_list, arg1) ;
va_start(arg1, arg0) ;

__ats_lab_loop1_11:
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (tmp34 == (ats_sum_ptr_type)0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
tmp39 = ats_caselptrlab_mac(anairiats_sum_7, tmp34, atslab_0) ;
tmp40 = ats_caselptrlab_mac(anairiats_sum_7, tmp34, atslab_1) ;
tmp35 = tmp33 ;
tmp36 = tmp39 ;
tmp37 = tmp40 ;
goto __ats_lab_loop2_12 ; // tail call
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
// if (tmp34 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_22_1:
tmp38 = ats_true_bool ;
break ;
} while (0) ;
return tmp38 ;

__ats_lab_loop2_12:
tmp42 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_8, tmp35), atslab_d1exp_node) ;
do {
/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)tmp42)->tag != 47) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp43 = ats_caselptrlab_mac(anairiats_sum_9, tmp42, atslab_1) ;
tmp44 = ats_caselptrlab_mac(anairiats_sum_9, tmp42, atslab_2) ;
tmp46 = p1at_arity_9 (tmp43) ;
tmp45 = atspre_eq_int_int (tmp36, tmp46) ;
if (tmp45) {
tmp33 = tmp44 ;
tmp34 = tmp37 ;
goto __ats_lab_loop1_11 ; // tail call
} else {
tmp41 = ats_false_bool ;
} /* end of [if] */
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)tmp42)->tag != 49) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp47 = ats_caselptrlab_mac(anairiats_sum_10, tmp42, atslab_2) ;
tmp35 = tmp47 ;
tmp36 = tmp36 ;
tmp37 = tmp37 ;
goto __ats_lab_loop2_12 ; // tail call
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)tmp42)->tag != 50) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp48 = ats_caselptrlab_mac(anairiats_sum_10, tmp42, atslab_2) ;
tmp35 = tmp48 ;
tmp36 = tmp36 ;
tmp37 = tmp37 ;
goto __ats_lab_loop2_12 ; // tail call
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)tmp42)->tag != 51) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
tmp49 = ats_caselptrlab_mac(anairiats_sum_10, tmp42, atslab_2) ;
tmp35 = tmp49 ;
tmp36 = tmp36 ;
tmp37 = tmp37 ;
goto __ats_lab_loop2_12 ; // tail call
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
__ats_lab_27_1:
tmp41 = ats_false_bool ;
break ;
} while (0) ;
return tmp41 ;

return (tmp50) ;
} /* end of [loop1_11_0loop2_12] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 2951(line=122, offs=4) -- 3515(line=137, offs=4)
*/
ATSstaticdec()
ats_bool_type
aritest_10 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp32) ;

__ats_lab_aritest_10:
tmp32 = loop1_11 (arg0, arg1) ;
return (tmp32) ;
} /* end of [aritest_10] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3584(line=142, offs=17) -- 3660(line=144, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def:
tmp54 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_get_artylst (arg0) ;
tmp53 = aritest_10 (arg1, tmp54) ;
return (tmp53) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2cst_match_def] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 3738(line=150, offs=5) -- 3978(line=156, offs=27)
*/
ATSstaticdec()
ats_ptr_type
d2exp_d2var_lvalize_15 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp55) ;
ATSlocal (ats_bool_type, tmp56) ;
ATSlocal (ats_bool_type, tmp57) ;

__ats_lab_d2exp_d2var_lvalize_15:
do {
/* branch: __ats_lab_28 */
__ats_lab_28_0:
__ats_lab_28_1:
tmp56 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_linear (arg1) ;
if (!tmp56) { goto __ats_lab_29_1 ; }
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp55)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_3, tmp55, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_3, tmp55, atslab_1, arg2) ;
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
__ats_lab_29_1:
tmp57 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2var_is_mutabl (arg1) ;
if (!tmp57) { goto __ats_lab_30_1 ; }
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp55)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_3, tmp55, atslab_0, arg1) ;
ats_selptrset_mac(anairiats_sum_3, tmp55, atslab_1, arg2) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
__ats_lab_30_1:
tmp55 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp55)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_2, tmp55, atslab_0, arg0) ;
break ;
} while (0) ;
return (tmp55) ;
} /* end of [d2exp_d2var_lvalize_15] */

/*
// /home/hwxi/research/Postiats/git/src/pats_dynexp2_util.dats: 4046(line=161, offs=3) -- 4700(line=189, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize:
tmp59 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)tmp59)->tag != 1) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
tmp60 = ats_caselptrlab_mac(anairiats_sum_2, tmp59, atslab_0) ;
tmp61 = (ats_sum_ptr_type)0 ;
tmp58 = d2exp_d2var_lvalize_15 (arg0, tmp60, tmp61) ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)tmp59)->tag != 38) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
tmp62 = ats_caselptrlab_mac(anairiats_sum_2, tmp59, atslab_0) ;
tmp63 = (ats_sum_ptr_type)0 ;
tmp58 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp58)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp58, atslab_0, tmp62) ;
ats_selptrset_mac(anairiats_sum_3, tmp58, atslab_1, tmp63) ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)tmp59)->tag != 35) { goto __ats_lab_37_0 ; }
__ats_lab_33_1:
tmp64 = ats_caselptrlab_mac(anairiats_sum_3, tmp59, atslab_0) ;
tmp65 = ats_caselptrlab_mac(anairiats_sum_3, tmp59, atslab_1) ;
tmp66 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, tmp64), atslab_d2exp_node) ;
do {
/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)tmp66)->tag != 1) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp67 = ats_caselptrlab_mac(anairiats_sum_2, tmp66, atslab_0) ;
tmp58 = d2exp_d2var_lvalize_15 (arg0, tmp67, tmp65) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)tmp66)->tag != 38) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp68 = ats_caselptrlab_mac(anairiats_sum_2, tmp66, atslab_0) ;
tmp58 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp58)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp58, atslab_0, tmp68) ;
ats_selptrset_mac(anairiats_sum_3, tmp58, atslab_1, tmp65) ;
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
__ats_lab_36_1:
tmp58 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp58)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_2, tmp58, atslab_0, arg0) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)tmp59)->tag != 37) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
tmp69 = ats_caselptrlab_mac(anairiats_sum_2, tmp59, atslab_0) ;
tmp58 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp58)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_2, tmp58, atslab_0, tmp69) ;
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (((ats_sum_ptr_type)tmp59)->tag != 41) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp70 = ats_caselptrlab_mac(anairiats_sum_11, tmp59, atslab_0) ;
tmp71 = ats_caselptrlab_mac(anairiats_sum_11, tmp59, atslab_1) ;
tmp72 = ats_caselptrlab_mac(anairiats_sum_11, tmp59, atslab_2) ;
tmp73 = ats_caselptrlab_mac(anairiats_sum_11, tmp59, atslab_3) ;
tmp58 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
((ats_sum_ptr_type)tmp58)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_11, tmp58, atslab_0, tmp70) ;
ats_selptrset_mac(anairiats_sum_11, tmp58, atslab_1, tmp71) ;
ats_selptrset_mac(anairiats_sum_11, tmp58, atslab_2, tmp72) ;
ats_selptrset_mac(anairiats_sum_11, tmp58, atslab_3, tmp73) ;
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
__ats_lab_39_1:
tmp58 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp58)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_2, tmp58, atslab_0, arg0) ;
break ;
} while (0) ;
return (tmp58) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__d2exp_lvalize] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp1_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp1_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp1_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_dynexp2_util_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e11_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_dynexp2_util_dats.c] */
